//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_chk
    {
        public int id { get; set; }
        public Nullable<decimal> totaladmin { get; set; }
        public Nullable<decimal> totaldlm { get; set; }
        public Nullable<decimal> totalrem { get; set; }
        public Nullable<decimal> totalapi { get; set; }
        public Nullable<decimal> totalsuper { get; set; }
        public Nullable<decimal> total { get; set; }
        public string details { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<decimal> totalwhitelabel { get; set; }
        public Nullable<decimal> totalVendor { get; set; }
        public Nullable<decimal> posremain { get; set; }
    }
}
