//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchivedTarget_History
    {
        public int Idno { get; set; }
        public string userid { get; set; }
        public string Role { get; set; }
        public Nullable<decimal> Total_TargetSet { get; set; }
        public string Opt_Type { get; set; }
        public Nullable<decimal> Total_Txn_amt { get; set; }
        public string Target_Type { get; set; }
        public string Achived_Perce { get; set; }
        public string Received_Perce { get; set; }
        public Nullable<decimal> rem_pre { get; set; }
        public Nullable<decimal> rem_post { get; set; }
        public string total_achived_amt { get; set; }
        public Nullable<decimal> Admin_Pre { get; set; }
        public Nullable<decimal> Admin_Post { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<System.DateTime> Achived_Date { get; set; }
    }
}
