//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_new_pass
    {
        public int idno { get; set; }
        public string transpass { get; set; }
        public string securitypass { get; set; }
        public Nullable<System.DateTime> lastupdatetrans { get; set; }
        public Nullable<System.DateTime> lastupdatesec { get; set; }
        public Nullable<int> transexpdays { get; set; }
        public Nullable<int> secexpdays { get; set; }
    }
}
