//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_details
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Photo { get; set; }
        public string CustomerCare_No { get; set; }
        public string Address { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string mobile1 { get; set; }
        public string mobile2 { get; set; }
        public string Gstno { get; set; }
        public string pencardno { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> District { get; set; }
        public string Aadhar { get; set; }
        public string AdminId { get; set; }
        public string WebsiteUrl { get; set; }
        public string localhost { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> RenivalDate { get; set; }
        public string Companyname { get; set; }
        public Nullable<int> pincode { get; set; }
        public string landmarkaddress { get; set; }
        public string pancardpath { get; set; }
        public string Aadhaarpath { get; set; }
        public string serciveaggrementpath { get; set; }
        public string tanno { get; set; }
        public string signaturepath { get; set; }
        public string registrationno { get; set; }
    }
}
