//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEPS_TXN_Details
    {
        public int Idno { get; set; }
        public string UserId { get; set; }
        public string MerchantTxnId { get; set; }
        public string AccountHolderAadhaar { get; set; }
        public string BankName { get; set; }
        public string BankRRN { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public decimal RemPre { get; set; }
        public decimal RemPost { get; set; }
        public decimal RemIncome { get; set; }
        public decimal RemGST { get; set; }
        public decimal DlmPre { get; set; }
        public decimal DlmPost { get; set; }
        public decimal DlmIncome { get; set; }
        public decimal DlmGST { get; set; }
        public decimal MdPre { get; set; }
        public decimal MdPost { get; set; }
        public decimal MdIncome { get; set; }
        public decimal MdGST { get; set; }
        public decimal AdminPre { get; set; }
        public decimal AdminPost { get; set; }
        public decimal AdminIncome { get; set; }
        public decimal AdminGST { get; set; }
        public decimal WlPre { get; set; }
        public decimal WlPost { get; set; }
        public decimal WlIncome { get; set; }
        public decimal WlGST { get; set; }
        public System.DateTime Txn_Date { get; set; }
        public string ApplicationType { get; set; }
        public string TerminalId { get; set; }
        public string Mobile { get; set; }
        public string Role { get; set; }
        public string timestamp { get; set; }
        public bool IsSettled { get; set; }
        public string SettledIn { get; set; }
        public string SettleType { get; set; }
        public Nullable<System.DateTime> SettledOn { get; set; }
        public Nullable<decimal> charge { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> customer_remain { get; set; }
        public string usernm { get; set; }
        public string deviceserialno { get; set; }
        public string devicename { get; set; }
        public string Devicetoken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ModelNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string InternetTYPE { get; set; }
        public string Address { get; set; }
        public string IPaddress { get; set; }
        public string videolink { get; set; }
        public string videostatus { get; set; }
    }
}
