//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeps_aadharpay_comm
    {
        public int idno { get; set; }
        public string DealerId { get; set; }
        public string RetailerId { get; set; }
        public string Retailer_name { get; set; }
        public string retailer_mobile { get; set; }
        public Nullable<decimal> AepsCharge { get; set; }
        public Nullable<decimal> AadharpayCharge { get; set; }
    }
}
