//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeps_comm_userwise
    {
        public int idno { get; set; }
        public string Userid { get; set; }
        public Nullable<decimal> aadharpay { get; set; }
        public Nullable<decimal> ministatement { get; set; }
        public Nullable<decimal> per_500_999 { get; set; }
        public Nullable<decimal> rs_500_999 { get; set; }
        public Nullable<decimal> maxrs_500_999 { get; set; }
        public string Type_500_999 { get; set; }
        public Nullable<decimal> per_1000_1499 { get; set; }
        public Nullable<decimal> rs_1000_1499 { get; set; }
        public Nullable<decimal> maxrs_1000_1499 { get; set; }
        public string Type_1000_1499 { get; set; }
        public Nullable<decimal> per_1500_1999 { get; set; }
        public Nullable<decimal> rs_1500_1999 { get; set; }
        public Nullable<decimal> maxrs_1500_1999 { get; set; }
        public string Type_1500_1999 { get; set; }
        public Nullable<decimal> per_2000_2499 { get; set; }
        public Nullable<decimal> rs_2000_2499 { get; set; }
        public Nullable<decimal> maxrs_2000_2499 { get; set; }
        public string Type_2000_2499 { get; set; }
        public Nullable<decimal> per_2500_2999 { get; set; }
        public Nullable<decimal> rs_2500_2999 { get; set; }
        public Nullable<decimal> maxrs_2500_2999 { get; set; }
        public string Type_2500_2999 { get; set; }
        public Nullable<decimal> per_3000_3499 { get; set; }
        public Nullable<decimal> rs_3000_3499 { get; set; }
        public Nullable<decimal> maxrs_3000_3499 { get; set; }
        public string Type_3000_3499 { get; set; }
        public Nullable<decimal> per_3500_5000 { get; set; }
        public Nullable<decimal> rs_3500_5000 { get; set; }
        public Nullable<decimal> maxrs_3500_5000 { get; set; }
        public string Type_3500_5000 { get; set; }
        public Nullable<decimal> per_5001_10000 { get; set; }
        public Nullable<decimal> rs_5001_10000 { get; set; }
        public Nullable<decimal> maxrs_5001_10000 { get; set; }
        public string Type_5001_10000 { get; set; }
    }
}
