//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEPS_Merchants
    {
        public string UserId { get; set; }
        public string UserType { get; set; }
        public string Pwd { get; set; }
        public string status { get; set; }
        public string LogoPath { get; set; }
        public string KYCPATH { get; set; }
        public string cancelledCheckPath { get; set; }
        public string ShopPanPath { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Retailer_Details Retailer_Details { get; set; }
    }
}
