//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport_info
    {
        public string Airport_Name { get; set; }
        public string Aiport_Code { get; set; }
        public string City_Name { get; set; }
        public string City_Code { get; set; }
        public string Country_name { get; set; }
        public string Country_Code { get; set; }
        public string Nationalty { get; set; }
        public string Currency { get; set; }
        public int idno { get; set; }
    }
}
