//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_update_url
    {
        public string APIID { get; set; }
        public string Updateurl { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int id { get; set; }
    }
}
