//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_user_details
    {
        public string apiid { get; set; }
        public string username { get; set; }
        public string farmname { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> district { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public Nullable<int> pincode { get; set; }
        public string emailid { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string status { get; set; }
        public string ipsts { get; set; }
        public Nullable<decimal> comm { get; set; }
        public string SlabName { get; set; }
        public string money_sts { get; set; }
        public string Photo { get; set; }
        public string pancard { get; set; }
        public string adharcard { get; set; }
        public string gst { get; set; }
        public Nullable<int> capping { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public string PSAStatus { get; set; }
        public string Position { get; set; }
        public string BusinessType { get; set; }
        public string Bankaccountno { get; set; }
        public string Ifsccode { get; set; }
        public string city { get; set; }
        public string accountholder { get; set; }
        public string bankname { get; set; }
        public string bankAddress { get; set; }
        public string pancardPath { get; set; }
        public string aadharcardPath { get; set; }
        public string frimregistrationPath { get; set; }
        public string AadhaarStatus { get; set; }
        public Nullable<System.DateTime> UpdateprofileDate { get; set; }
        public string Registractioncertificatepath { get; set; }
        public string serviceagreementpath { get; set; }
        public string AddressProofpath { get; set; }
        public string AepsMposstatus { get; set; }
        public string Mpossts { get; set; }
        public string Flighsts { get; set; }
        public string Bussts { get; set; }
        public string Hotelsts { get; set; }
        public string pancardsts { get; set; }
        public string Indonepalsts { get; set; }
        public string giftcardsts { get; set; }
        public Nullable<bool> moneysts { get; set; }
        public string gststatus { get; set; }
        public Nullable<bool> IsAgreement { get; set; }
        public string Agreementpath { get; set; }
        public string BackSideAadharcardphoto { get; set; }
        public string APPLOGIN_STS { get; set; }
    }
}
