//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_remain_amount
    {
        public string apiid { get; set; }
        public string groupname { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int idno { get; set; }
    }
}
