//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Api_upload_gst
    {
        public int idno { get; set; }
        public string Apiid { get; set; }
        public string monthchk { get; set; }
        public string yearchk { get; set; }
        public string status { get; set; }
        public string uploadfile { get; set; }
        public string reason { get; set; }
    }
}
