//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiCallBackURL
    {
        public int idno { get; set; }
        public int id { get; set; }
        public string Requesttype { get; set; }
        public string bodytype { get; set; }
        public string keystatus { get; set; }
        public string valstatussuccess { get; set; }
        public string valstatusfailed { get; set; }
        public string keyrchid { get; set; }
        public string keymsg { get; set; }
        public string keyoperatorid { get; set; }
        public string keybalance { get; set; }
    
        public virtual RechargeapiInfo RechargeapiInfo { get; set; }
    }
}
