//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appicon
    {
        public int idno { get; set; }
        public string color1 { get; set; }
        public string color2 { get; set; }
        public string background_color { get; set; }
        public string icon_design { get; set; }
        public Nullable<bool> istrue { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string theam { get; set; }
        public string users { get; set; }
        public Nullable<bool> isFinancialtrue { get; set; }
        public Nullable<bool> isTraveltrue { get; set; }
        public Nullable<bool> isOtherstrue { get; set; }
        public Nullable<bool> isCmstrue { get; set; }
    }
}
