//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoCreditTransfer
    {
        public int idno { get; set; }
        public string remid { get; set; }
        public Nullable<System.DateTime> transferdate { get; set; }
        public Nullable<decimal> transferamount { get; set; }
        public Nullable<decimal> Rem_minimiumamnt { get; set; }
        public string transfertype { get; set; }
        public Nullable<System.DateTime> remupdatestatusdate { get; set; }
        public string remcurrentstatus { get; set; }
        public string Transfermessage { get; set; }
        public Nullable<int> fundtransfercount { get; set; }
        public Nullable<int> Totalfundytranfersete { get; set; }
        public Nullable<decimal> MaxCredit { get; set; }
    }
}
