//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_fund_transfer
    {
        public int idno { get; set; }
        public Nullable<decimal> txnamt { get; set; }
        public Nullable<System.DateTime> txndate { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string apirequest { get; set; }
        public string apiresponse { get; set; }
        public Nullable<decimal> apiremain { get; set; }
        public string accountno { get; set; }
        public string ifsccode { get; set; }
        public string PayeeName { get; set; }
        public string bankName { get; set; }
        public string comment { get; set; }
        public string apiname { get; set; }
        public string FundType { get; set; }
        public string bankrrn { get; set; }
        public string Mode { get; set; }
    }
}
