//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class autofundtransfer_master_to_dealer
    {
        public int idno { get; set; }
        public string dlmid { get; set; }
        public string masterid { get; set; }
        public Nullable<decimal> minamount { get; set; }
        public Nullable<decimal> Transferamount { get; set; }
        public string types { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updatedatetime { get; set; }
        public Nullable<int> totaltransfer { get; set; }
        public Nullable<System.DateTime> last_transfer { get; set; }
    }
}
