//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class backroundColorofapp
    {
        public int idno { get; set; }
        public string background_color1 { get; set; }
        public string background_color2 { get; set; }
        public string valuex { get; set; }
        public string valuey { get; set; }
    }
}
