//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountForAep
    {
        public int id { get; set; }
        public string RetailerId { get; set; }
        public string BankName { get; set; }
        public string AccountNO { get; set; }
        public string IFSC_CODE { get; set; }
        public string AccountHolder { get; set; }
        public Nullable<System.DateTime> InserDate { get; set; }
        public string Otp { get; set; }
        public string BankAddress { get; set; }
    }
}
