//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bharatpaygetwayinfo
    {
        public int idno { get; set; }
        public string token { get; set; }
        public string upiid { get; set; }
        public string session { get; set; }
    }
}
