//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusCancellationDetail
    {
        public int idno { get; set; }
        public decimal FareAmount { get; set; }
        public decimal AddCharge { get; set; }
        public decimal UpdateFareWithAmt { get; set; }
        public decimal CancallationCharge { get; set; }
        public string RetailerId { get; set; }
        public decimal RemPre { get; set; }
        public decimal RemPost { get; set; }
        public decimal AdminPre { get; set; }
        public decimal AdminPost { get; set; }
        public string EndUserIp { get; set; }
        public string PNR { get; set; }
        public string TraceId { get; set; }
        public string sourceStationName { get; set; }
        public string destinationStationName { get; set; }
        public System.DateTime dateOfJourney { get; set; }
        public string LeadPaxFirstName { get; set; }
        public string LeadPaxLastName { get; set; }
        public string PassengerName { get; set; }
        public string BusOptName { get; set; }
        public string BoardingLocation { get; set; }
        public string DropingLocation { get; set; }
        public string BoardingTime { get; set; }
        public string DropingTime { get; set; }
        public System.DateTime TicketDate { get; set; }
        public System.DateTime CancellationDate { get; set; }
        public string RequestJson { get; set; }
        public string ResponseJson { get; set; }
    }
}
