//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusTicketingDetail
    {
        public int idno { get; set; }
        public decimal FareAmount { get; set; }
        public decimal AddCharge { get; set; }
        public decimal UpdateFareWithAmt { get; set; }
        public string RetailerId { get; set; }
        public string Status { get; set; }
        public string TicketStatus { get; set; }
        public decimal RemPre { get; set; }
        public decimal RemPost { get; set; }
        public decimal RemInc { get; set; }
        public decimal DlmPre { get; set; }
        public decimal DlmPost { get; set; }
        public decimal DlmInc { get; set; }
        public decimal MdPre { get; set; }
        public decimal MdPost { get; set; }
        public decimal MdInc { get; set; }
        public decimal WlPre { get; set; }
        public decimal WlPost { get; set; }
        public decimal WlInc { get; set; }
        public decimal AdminPre { get; set; }
        public decimal AdminPost { get; set; }
        public decimal AdminInc { get; set; }
        public string EndUserIp { get; set; }
        public string PNR { get; set; }
        public string TicketNo { get; set; }
        public string TraceId { get; set; }
        public string sourceStationName { get; set; }
        public string destinationStationName { get; set; }
        public System.DateTime dateOfJourney { get; set; }
        public string LeadPaxFirstName { get; set; }
        public string LeadPaxLastName { get; set; }
        public string PassengerName { get; set; }
        public string BusOptName { get; set; }
        public string BusId { get; set; }
        public string BoardingLocation { get; set; }
        public string DropingLocation { get; set; }
        public string BoardingTime { get; set; }
        public string DropingTime { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string RequestJson { get; set; }
        public string ResponseJson { get; set; }
        public string selectedSeats { get; set; }
        public Nullable<decimal> pubfare { get; set; }
        public Nullable<int> totalseat { get; set; }
        public Nullable<decimal> remtds { get; set; }
        public Nullable<decimal> dlmtds { get; set; }
        public Nullable<decimal> mdtds { get; set; }
        public string IPaddress { get; set; }
        public string Devicetoken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ModelNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string InternetTYPE { get; set; }
        public string Address { get; set; }
    }
}
