//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Idno { get; set; }
        public int ProductId { get; set; }
        public string SellerId { get; set; }
        public string BuyerId { get; set; }
        public decimal ListPrice { get; set; }
        public decimal StandardPrice { get; set; }
        public int Qty { get; set; }
        public short OrderStatus { get; set; }
    }
}
