//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_DMT_New_Comm
    {
        public int idno { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Retailer_charge { get; set; }
        public Nullable<decimal> Dealer_comm { get; set; }
        public Nullable<decimal> Master_comm { get; set; }
        public Nullable<decimal> Api_charge { get; set; }
        public Nullable<decimal> Whitelabel_charge { get; set; }
        public Nullable<bool> gst_sts { get; set; }
        public Nullable<bool> tds_sts { get; set; }
        public Nullable<decimal> purchase { get; set; }
    }
}
