//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_Microatm_comm
    {
        public int idno { get; set; }
        public string usertype { get; set; }
        public string cardtype { get; set; }
        public string cardcategorytype { get; set; }
        public string cardname { get; set; }
        public Nullable<decimal> minvalue { get; set; }
        public Nullable<decimal> maxvalue { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string chargetype { get; set; }
    }
}
