//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comm_daywiseslab
    {
        public int idno { get; set; }
        public string Role { get; set; }
        public Nullable<decimal> Comm_2000_5000 { get; set; }
        public Nullable<decimal> Comm_5001_10000 { get; set; }
        public Nullable<decimal> Comm_10001_max { get; set; }
    }
}
