//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_whitelabel_Mpos_comm
    {
        public int idno { get; set; }
        public string usertype { get; set; }
        public Nullable<decimal> CashWithdraw { get; set; }
        public Nullable<decimal> Salesdebitupto2000 { get; set; }
        public Nullable<decimal> Salesdebitabove2000 { get; set; }
        public Nullable<decimal> SalescreditNormal { get; set; }
        public Nullable<decimal> Salescreditgrocery { get; set; }
        public Nullable<decimal> SalescreditEduandInsu { get; set; }
        public string whitelabelid { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> prepaidcard { get; set; }
        public Nullable<decimal> maxcashcomm { get; set; }
    }
}
