//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creaditcard_comm
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public string role { get; set; }
        public Nullable<decimal> comm_100_5000 { get; set; }
        public Nullable<decimal> comm_5001_10000 { get; set; }
        public Nullable<decimal> comm_10001_25000 { get; set; }
        public Nullable<decimal> comm_25001_50000 { get; set; }
        public Nullable<decimal> comm_50001_75000 { get; set; }
        public Nullable<decimal> comm_75001_100000 { get; set; }
    }
}
