//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_IMPS_Charge
    {
        public int idno { get; set; }
        public Nullable<decimal> min { get; set; }
        public Nullable<decimal> max { get; set; }
        public Nullable<decimal> comm { get; set; }
        public string type { get; set; }
    }
}
