//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customersupports_times
    {
        public int idno { get; set; }
        public string nameofday { get; set; }
        public Nullable<System.DateTime> openingtime { get; set; }
        public Nullable<System.DateTime> clossingtime { get; set; }
        public string status { get; set; }
    }
}
