//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cyberplate_info
    {
        public int idnno { get; set; }
        public string sdcode { get; set; }
        public string apcode { get; set; }
        public string opcode { get; set; }
        public string password { get; set; }
        public string keypath { get; set; }
        public string dealercode { get; set; }
        public string certcode { get; set; }
    }
}
