//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyber_plate_code
    {
        public int idno { get; set; }
        public string Own_code { get; set; }
        public string Cyber_code_verify { get; set; }
        public string Cyber_code_Payment { get; set; }
        public string Cyber_code_Status { get; set; }
    }
}
