//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daywisesettelecomm
    {
        public int idno { get; set; }
        public string role { get; set; }
        public Nullable<decimal> minamount { get; set; }
        public Nullable<decimal> maxamount { get; set; }
        public Nullable<int> dayscounts { get; set; }
        public Nullable<decimal> sharedcomm { get; set; }
        public Nullable<bool> sts { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
    }
}
