//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daywisecomm
    {
        public int idno { get; set; }
        public string role { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<decimal> remainpre { get; set; }
        public Nullable<decimal> remainpost { get; set; }
        public string dealerid { get; set; }
        public Nullable<decimal> dlmcomm { get; set; }
        public Nullable<decimal> dlmpre { get; set; }
        public Nullable<decimal> dlmpost { get; set; }
        public string mdid { get; set; }
        public Nullable<decimal> mdcomm { get; set; }
        public Nullable<decimal> mdpre { get; set; }
        public Nullable<decimal> mdpost { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
