//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dealer_sim_new
    {
        public int idno { get; set; }
        public string dlmid { get; set; }
        public string opt_code { get; set; }
        public string Zone { get; set; }
        public string USERID { get; set; }
        public string Password { get; set; }
        public string RechargePin { get; set; }
        public string Imeino { get; set; }
        public Nullable<int> DaylimitMax { get; set; }
        public string Etopminbal { get; set; }
        public string posid { get; set; }
        public string Macaddress { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> remaining { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> checks { get; set; }
        public Nullable<bool> login { get; set; }
    }
}
