//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dealer_sim
    {
        public int idno { get; set; }
        public string dlmid { get; set; }
        public string OperatorCode { get; set; }
        public Nullable<decimal> dailyhome_limit { get; set; }
        public Nullable<decimal> dailyrom_limit { get; set; }
        public string circle { get; set; }
        public Nullable<int> simnumber { get; set; }
        public string simname { get; set; }
        public string userid { get; set; }
        public string password { get; set; }
        public string pin { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> remainbal { get; set; }
        public Nullable<decimal> totalrecharge { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public Nullable<decimal> purchasecomm { get; set; }
    }
}
