//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_Details
    {
        public string SSId { get; set; }
        public string DealerId { get; set; }
        public string DealerName { get; set; }
        public Nullable<System.DateTime> DOF { get; set; }
        public string FarmName { get; set; }
        public int State { get; set; }
        public int District { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Photo { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> commission { get; set; }
        public string slab_name { get; set; }
        public string pancard { get; set; }
        public string adharcard { get; set; }
        public string gst { get; set; }
        public string createdby { get; set; }
        public string DefaultStatus { get; set; }
        public string PSAStatus { get; set; }
        public string Position { get; set; }
        public string BusinessType { get; set; }
        public string Bankaccountno { get; set; }
        public string Ifsccode { get; set; }
        public string city { get; set; }
        public string accountholder { get; set; }
        public string bankname { get; set; }
        public string bankAddress { get; set; }
        public string pancardPath { get; set; }
        public string aadharcardPath { get; set; }
        public string frimregistrationPath { get; set; }
        public string AadhaarStatus { get; set; }
        public Nullable<System.DateTime> UpdateprofileDate { get; set; }
        public string Registractioncertificatepath { get; set; }
        public string serviceagreementpath { get; set; }
        public string AddressProofpath { get; set; }
        public Nullable<bool> moneysts { get; set; }
        public string AepsMposstatus { get; set; }
        public string Mpossts { get; set; }
        public string Flighsts { get; set; }
        public string Bussts { get; set; }
        public string Hotelsts { get; set; }
        public string pancardsts { get; set; }
        public string Indonepalsts { get; set; }
        public string giftcardsts { get; set; }
        public string Agreementpath { get; set; }
        public Nullable<bool> IsAgreement { get; set; }
        public string FinincialRolesType { get; set; }
        public string gststatus { get; set; }
        public string TransPIN { get; set; }
        public string BackSideAadharcardphoto { get; set; }
        public string APPLOGIN_STS { get; set; }
        public Nullable<bool> chargeback_otpsts { get; set; }
        public Nullable<bool> DealerSelf_sts { get; set; }
        public int caption { get; set; }
        public string NetOFFR { get; set; }
        public Nullable<bool> moneysts1 { get; set; }
        public Nullable<bool> moneyppi { get; set; }
        public Nullable<bool> payout { get; set; }
    }
}
