//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_To_Retailer_Balance
    {
        public string RetailerId { get; set; }
        public string DealerId { get; set; }
        public Nullable<System.DateTime> RechargeDate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int id { get; set; }
        public Nullable<decimal> remain_amount { get; set; }
        public Nullable<decimal> remain_amount_dealer { get; set; }
        public Nullable<decimal> remain_pre_amount { get; set; }
        public Nullable<decimal> remain_pre_amount_dealer { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<decimal> finalbal { get; set; }
        public string bal_type { get; set; }
        public Nullable<decimal> oldcrbalance { get; set; }
        public Nullable<decimal> cr { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> TotalBal { get; set; }
        public string fundby { get; set; }
        public string CollectionBy { get; set; }
        public string BankName { get; set; }
        public string Admin_AccountNo { get; set; }
        public Nullable<decimal> gst { get; set; }
        public string Head { get; set; }
        public string Transectionid { get; set; }
        public Nullable<decimal> margine { get; set; }
    }
}
