//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class default_postpaid_comm
    {
        public int idno { get; set; }
        public string optid { get; set; }
        public Nullable<decimal> comm1 { get; set; }
        public Nullable<decimal> comm2 { get; set; }
        public Nullable<decimal> comm3 { get; set; }
        public string comm4 { get; set; }
        public string createdby { get; set; }
        public string createdfor { get; set; }
    }
}
