//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleteUserHistory
    {
        public int idno { get; set; }
        public string Email { get; set; }
        public string FarmName { get; set; }
        public string Name { get; set; }
        public string ContectNo { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<decimal> RecoveryAmount { get; set; }
    }
}
