//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deletedApprveBankInfo
    {
        public int Idno { get; set; }
        public string UserId { get; set; }
        public string AcconutHolderName { get; set; }
        public string BankAccountNo { get; set; }
        public string IFSC_CODE { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Address { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public string Email { get; set; }
        public string Firm_Name { get; set; }
        public string CancelCheckFile { get; set; }
        public Nullable<System.DateTime> deleteddate { get; set; }
    }
}
