//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dlm_to_rem_margine
    {
        public int idno { get; set; }
        public string remid { get; set; }
        public string dlmid { get; set; }
        public Nullable<decimal> marginecomm { get; set; }
    }
}
