//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DthConnection_common_comm
    {
        public int idno { get; set; }
        public string optcode { get; set; }
        public Nullable<decimal> mastercomm { get; set; }
        public Nullable<decimal> dlmcomm { get; set; }
        public Nullable<decimal> retailercomm { get; set; }
        public Nullable<decimal> whitelabelcomm { get; set; }
        public Nullable<decimal> apicomm { get; set; }
    }
}
