//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DthOperatorsSetTopBoxMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DthOperatorsSetTopBoxMapping()
        {
            this.DthPlanAndSpecifications = new HashSet<DthPlanAndSpecification>();
        }
    
        public int Id { get; set; }
        public int OperatorId { get; set; }
        public int SetTopBoxId { get; set; }
    
        public virtual DthOperator DthOperator { get; set; }
        public virtual DthSetTopBox DthSetTopBox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DthPlanAndSpecification> DthPlanAndSpecifications { get; set; }
    }
}
