//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DthSetTopBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DthSetTopBox()
        {
            this.DthOperatorsSetTopBoxMappings = new HashSet<DthOperatorsSetTopBoxMapping>();
        }
    
        public int Id { get; set; }
        public string BoxType { get; set; }
        public string BoxTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DthOperatorsSetTopBoxMapping> DthOperatorsSetTopBoxMappings { get; set; }
    }
}
