//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcommTransactionHistory
    {
        public int Idno { get; set; }
        public int OrderId { get; set; }
        public string BuyerId { get; set; }
        public string BuyerRole { get; set; }
        public string VenderId { get; set; }
        public int ProductId { get; set; }
        public decimal ListPrice { get; set; }
        public decimal StandardPrice { get; set; }
        public int QTY { get; set; }
        public decimal Amount { get; set; }
        public short OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int DOTP { get; set; }
        public int DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DeliveredOn { get; set; }
    }
}
