//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_show_passcode
    {
        public int id { get; set; }
        public string passcode { get; set; }
        public Nullable<bool> forgetotp { get; set; }
        public Nullable<bool> cr_status { get; set; }
        public Nullable<bool> whatsappapists { get; set; }
    }
}
