//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class failed_recharge_move
    {
        public int idno { get; set; }
        public string operator_code { get; set; }
        public string api_name { get; set; }
        public string status { get; set; }
        public string ApiPort { get; set; }
    }
}
