//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Failed_Login_info
    {
        public int Idno { get; set; }
        public string EmailId { get; set; }
        public string pwd { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string LoginFrom { get; set; }
        public string IP_Address { get; set; }
        public string browser { get; set; }
        public string Macaddress { get; set; }
        public string latitude { get; set; }
        public string Logitude { get; set; }
        public string Location { get; set; }
        public string city { get; set; }
    }
}
