//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeCollector_details
    {
        public string FCId { get; set; }
        public string FCName { get; set; }
        public string FirmName { get; set; }
        public int State { get; set; }
        public int District { get; set; }
        public string Mobile { get; set; }
        public string SchoolName { get; set; }
        public int Installments { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> CommissionAdmin { get; set; }
        public Nullable<decimal> CommissionMD { get; set; }
        public Nullable<decimal> CommissionDLM { get; set; }
        public Nullable<decimal> CommissionREM { get; set; }
        public Nullable<decimal> CommissionWL { get; set; }
        public string pancard { get; set; }
        public string adharcard { get; set; }
        public string gst { get; set; }
        public string Photo { get; set; }
        public string deviceid { get; set; }
        public string CreatedBy { get; set; }
        public string Logo { get; set; }
    }
}
