//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeCollectionInvoice
    {
        public int INVOICEID { get; set; }
        public string UserId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
