//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinoGenerateUrl
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string reqid { get; set; }
        public string request { get; set; }
        public string response { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
