//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedFeeCharge
    {
        public int Idno { get; set; }
        public string FeeName { get; set; }
        public decimal FeeValue { get; set; }
        public string stdClass { get; set; }
        public string FCID { get; set; }
    }
}
