//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Commission_whitelabel
    {
        public int idno { get; set; }
        public Nullable<decimal> WDealerCommission { get; set; }
        public Nullable<decimal> WRetailerCommission { get; set; }
        public Nullable<decimal> WhitelabelCommission { get; set; }
        public string WhitelabelId { get; set; }
    }
}
