//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Commission_admin
    {
        public int idno { get; set; }
        public Nullable<decimal> MDCommission { get; set; }
        public Nullable<decimal> DealerCommission { get; set; }
        public Nullable<decimal> RetailerCommission { get; set; }
        public Nullable<decimal> WhitelabelCommission { get; set; }
    }
}
