//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class forgottable
    {
        public int indo { get; set; }
        public string Userid { get; set; }
        public string Roles { get; set; }
        public string Email { get; set; }
        public string forgotlink { get; set; }
        public string adminid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
