//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gateway_Auth
    {
        public int idno { get; set; }
        public string merchantkey { get; set; }
        public string merchantsalt { get; set; }
        public string authheader { get; set; }
        public string Merchantid { get; set; }
    }
}
