//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gateway_recharge
    {
        public int idno { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> rch_time { get; set; }
        public string rch_from { get; set; }
        public string rch_type { get; set; }
        public string Uniqueid { get; set; }
        public string op1 { get; set; }
        public string op2 { get; set; }
        public string op3 { get; set; }
        public string op4 { get; set; }
        public string Status { get; set; }
        public string billduedate { get; set; }
        public Nullable<decimal> servicefee { get; set; }
        public Nullable<System.DateTime> responsetime { get; set; }
    }
}
