//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCard
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> MinimumAmt { get; set; }
        public Nullable<decimal> MaximumAmt { get; set; }
        public Nullable<decimal> FirstAmt { get; set; }
        public Nullable<decimal> SecondAmt { get; set; }
        public Nullable<decimal> ThirdAmt { get; set; }
        public Nullable<decimal> FourthAmt { get; set; }
        public string userid { get; set; }
        public string GiftName { get; set; }
        public string GiftImage { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
