//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPrice
    {
        public int idno { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> RoomPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> ExtraGuestCharge { get; set; }
        public Nullable<decimal> ChildCharge { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PublishedPrice { get; set; }
        public Nullable<decimal> PublishedPriceRoundedOff { get; set; }
        public Nullable<decimal> OfferedPrice { get; set; }
        public Nullable<decimal> OfferedPriceRoundedOff { get; set; }
        public Nullable<decimal> AgentCommission { get; set; }
        public Nullable<decimal> AgentMarkUp { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public string AgentRefno { get; set; }
        public string retailerid { get; set; }
    }
}
