//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPassenger
    {
        public int idno { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> LeadPassenger { get; set; }
        public string Age { get; set; }
        public string AgentRefno { get; set; }
        public string retailerid { get; set; }
        public int PaxType { get; set; }
        public string Phoneno { get; set; }
        public string PassportNo { get; set; }
        public System.DateTime PassportIssueDate { get; set; }
        public System.DateTime PassportExpDate { get; set; }
    }
}
