//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelCancellation
    {
        public int Idno { get; set; }
        public Nullable<int> RequestType { get; set; }
        public string Remarks { get; set; }
        public string ChangeRequestStatus { get; set; }
        public Nullable<int> ChangeRequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string CancelRequestJson { get; set; }
        public string CancelRequestStatusResponseJson { get; set; }
        public string TraceId { get; set; }
        public Nullable<decimal> RefundedAmount { get; set; }
        public Nullable<decimal> CancellationCharge { get; set; }
        public Nullable<decimal> CancellationMarkup { get; set; }
    
        public virtual Hotel_info Hotel_info { get; set; }
    }
}
