//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imps2_common_comm_new
    {
        public int idno { get; set; }
        public string usertype { get; set; }
        public Nullable<decimal> Verify_comm { get; set; }
        public Nullable<decimal> Comm_1000 { get; set; }
        public Nullable<decimal> Comm_2000 { get; set; }
        public Nullable<decimal> Comm_3000 { get; set; }
        public Nullable<decimal> Comm_4000 { get; set; }
        public Nullable<decimal> Comm_5000 { get; set; }
        public Nullable<bool> gst_sts { get; set; }
        public Nullable<bool> tds_sts { get; set; }
    }
}
