//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imps2_api_comm_new
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> comm_1000 { get; set; }
        public Nullable<decimal> comm_2000 { get; set; }
        public Nullable<decimal> comm_3000 { get; set; }
        public Nullable<decimal> comm_4000 { get; set; }
        public Nullable<decimal> comm_5000 { get; set; }
        public Nullable<bool> gst_sts { get; set; }
        public Nullable<bool> tds_sts { get; set; }
        public Nullable<decimal> verify_comm { get; set; }
    }
}
