//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPS_transtion_detsils_old
    {
        public int idno { get; set; }
        public string trans_common_id { get; set; }
        public string trans_id { get; set; }
        public string accountno { get; set; }
        public string ifsccode { get; set; }
        public string bank_nm { get; set; }
        public string senderno { get; set; }
        public string bank_trans_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public string rch_from { get; set; }
        public Nullable<System.DateTime> trans_time { get; set; }
        public string Trans_Type { get; set; }
        public string trans_from { get; set; }
        public Nullable<System.DateTime> Response_time { get; set; }
        public string api_name { get; set; }
        public Nullable<decimal> purchase { get; set; }
        public Nullable<decimal> income { get; set; }
        public Nullable<decimal> md_income { get; set; }
        public Nullable<decimal> dlm_income { get; set; }
        public Nullable<decimal> user_remain { get; set; }
        public Nullable<decimal> dlm_remain { get; set; }
        public Nullable<decimal> md_remain { get; set; }
        public Nullable<decimal> charge { get; set; }
        public string Status { get; set; }
        public string Response_output { get; set; }
        public string Request { get; set; }
        public string kycstatus { get; set; }
        public string ipaddress { get; set; }
        public string macaddress { get; set; }
        public string imeino { get; set; }
        public string recivername { get; set; }
        public Nullable<decimal> user_remain_pre { get; set; }
        public Nullable<decimal> dlm_remain_pre { get; set; }
        public Nullable<decimal> md_remain_pre { get; set; }
        public Nullable<decimal> Cashback { get; set; }
        public string api_request { get; set; }
        public string api_response { get; set; }
        public Nullable<decimal> Api_remain_pre { get; set; }
        public Nullable<decimal> Api_remain_post { get; set; }
        public Nullable<decimal> purchase_comm { get; set; }
        public Nullable<decimal> gst_comm { get; set; }
        public Nullable<decimal> md_comm { get; set; }
        public Nullable<decimal> md_gst { get; set; }
        public Nullable<decimal> dlm_comm { get; set; }
        public Nullable<decimal> dlm_gst { get; set; }
        public Nullable<decimal> rem_comm { get; set; }
        public Nullable<decimal> rem_gst { get; set; }
        public Nullable<decimal> api_comm { get; set; }
        public Nullable<decimal> api_gst { get; set; }
        public Nullable<decimal> whitelabel_comm { get; set; }
        public Nullable<decimal> whitelabel_gst { get; set; }
        public Nullable<decimal> whitelabel_totalcomm { get; set; }
        public string user_type { get; set; }
        public Nullable<decimal> customer_fee { get; set; }
        public Nullable<decimal> customer_fee_gst { get; set; }
        public Nullable<decimal> customer_fee_net_amount { get; set; }
        public Nullable<decimal> rem_comm_include_gst { get; set; }
        public Nullable<decimal> rem_comm_net_amount { get; set; }
        public Nullable<decimal> rem_comm_tds { get; set; }
        public Nullable<decimal> dlm_comm_include_gst { get; set; }
        public Nullable<decimal> dlm_comm_net_amount { get; set; }
        public Nullable<decimal> dlm_comm_tds { get; set; }
        public Nullable<decimal> md_comm_include_gst { get; set; }
        public Nullable<decimal> md_comm_net_amount { get; set; }
        public Nullable<decimal> md_comm_tds { get; set; }
        public Nullable<decimal> total_tds { get; set; }
        public Nullable<decimal> admin_comm_include_gst { get; set; }
        public Nullable<decimal> admin_comm_netamount { get; set; }
        public Nullable<decimal> admin_comm_tds { get; set; }
        public Nullable<decimal> share_rem_comm { get; set; }
        public Nullable<decimal> share_md_comm { get; set; }
        public Nullable<decimal> share_admin_comm { get; set; }
        public Nullable<decimal> admin_comm { get; set; }
        public Nullable<decimal> total_admin_gst { get; set; }
        public Nullable<decimal> total_admin_tds { get; set; }
        public Nullable<decimal> rem_settlement { get; set; }
        public Nullable<decimal> share_dlm_comm { get; set; }
        public Nullable<decimal> whitelabel_income { get; set; }
        public Nullable<decimal> whitelabel_remain { get; set; }
        public Nullable<decimal> whitelabel_remain_pre { get; set; }
        public Nullable<decimal> whitelabel_comm_include_gst { get; set; }
        public Nullable<decimal> whitelabel_comm_net_amount { get; set; }
        public Nullable<decimal> whitelabel_comm_tds { get; set; }
        public Nullable<decimal> share_whitelabel_comm { get; set; }
        public Nullable<decimal> api_income { get; set; }
        public Nullable<decimal> api_commapi_gst { get; set; }
        public Nullable<decimal> api_comm_include_gst { get; set; }
        public Nullable<decimal> api_comm_net_amount { get; set; }
        public Nullable<decimal> api_comm_tds { get; set; }
        public Nullable<decimal> share_api_comm { get; set; }
        public Nullable<decimal> api_settlement { get; set; }
        public string DmtType { get; set; }
        public string idprooftype { get; set; }
        public string idproofno { get; set; }
        public string Whitelabelid { get; set; }
        public string Devicetoken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ModelNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string InternetTYPE { get; set; }
        public string Address { get; set; }
        public string PhotoCaptured { get; set; }
        public string uniqueid { get; set; }
    }
}
