//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndoNepalSender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndoNepalSender()
        {
            this.IndoNepalBeneficiaries = new HashSet<IndoNepalBeneficiary>();
        }
    
        public int Idno { get; set; }
        public string sendername { get; set; }
        public string sendergender { get; set; }
        public string employer { get; set; }
        public string senderaddress { get; set; }
        public string sendermobile { get; set; }
        public string senderidtype { get; set; }
        public string senderidnumber { get; set; }
        public string Docfilename { get; set; }
        public string image_url { get; set; }
        public bool IsApproved { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime senderdob { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndoNepalBeneficiary> IndoNepalBeneficiaries { get; set; }
    }
}
