//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndoNepalBeneficiary
    {
        public int BenIdno { get; set; }
        public int senderId { get; set; }
        public string receivername { get; set; }
        public string receivergender { get; set; }
        public string receiveraddress { get; set; }
        public string receivermobile { get; set; }
        public string branchid { get; set; }
        public string accountnumber { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual IndoNepalSender IndoNepalSender { get; set; }
    }
}
