//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instantpay_auth
    {
        public int idno { get; set; }
        public string authcode { get; set; }
        public string clientid { get; set; }
        public string clientsecret { get; set; }
        public string endpointip { get; set; }
        public string accountnumber { get; set; }
    }
}
