//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRCTC_COMMON_SLAB
    {
        public int idno { get; set; }
        public Nullable<decimal> tokenvalue { get; set; }
        public Nullable<decimal> dlmremtokenvalue { get; set; }
        public Nullable<decimal> mdtokencomm { get; set; }
        public Nullable<decimal> dlmtokencomm { get; set; }
        public Nullable<decimal> retailertoken { get; set; }
        public Nullable<decimal> Whitelabeltoken { get; set; }
        public Nullable<decimal> apitoken { get; set; }
    }
}
