//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KotakQRDetail
    {
        public int Idno { get; set; }
        public string Retailerid { get; set; }
        public decimal Amount { get; set; }
        public string GatewayReferenceId { get; set; }
        public string GatewayResponseMessage { get; set; }
        public string GatewayResponseStatus { get; set; }
        public string GatewayTransactionId { get; set; }
        public string MerchantChannelId { get; set; }
        public string MerchantId { get; set; }
        public string MerchantRequestId { get; set; }
        public string PayeeMcc { get; set; }
        public string PayeeVpa { get; set; }
        public string PayeeName { get; set; }
        public string PayerAccBin { get; set; }
        public string PayerActype { get; set; }
        public string PayerIfsc { get; set; }
        public string PayerName { get; set; }
        public string PayerVpa { get; set; }
        public string SubMerchantChannelId { get; set; }
        public string SubMerchantId { get; set; }
        public string TransactionTimestamp { get; set; }
        public string Type { get; set; }
        public string RetailerMobile { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string APIRequest { get; set; }
        public string APIResponse { get; set; }
        public decimal RemainPre { get; set; }
        public decimal RemainPost { get; set; }
        public decimal AdminRemainPre { get; set; }
        public decimal AdminRemainPost { get; set; }
        public string Status { get; set; }
        public string CallBackResponse { get; set; }
        public string Responsemessage { get; set; }
        public string Customertype { get; set; }
    }
}
