//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LapuDetail
    {
        public decimal idno { get; set; }
        public string SimNo { get; set; }
        public string Code { get; set; }
        public string pin { get; set; }
        public string method { get; set; }
        public string simName { get; set; }
        public string ActiveSts { get; set; }
        public string SimBal { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> minbal { get; set; }
        public Nullable<int> smscount { get; set; }
        public Nullable<decimal> maxrch { get; set; }
        public Nullable<System.DateTime> rdate { get; set; }
        public string remname { get; set; }
        public Nullable<decimal> maxdaylimit { get; set; }
        public Nullable<decimal> maxmonthlimit { get; set; }
        public string userid { get; set; }
        public string browser { get; set; }
        public Nullable<decimal> purchase { get; set; }
        public string imeino { get; set; }
    }
}
