//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanrequest
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> months { get; set; }
        public Nullable<System.DateTime> requesttime { get; set; }
        public Nullable<System.DateTime> responsetime { get; set; }
        public Nullable<System.DateTime> minserverloandate { get; set; }
        public string loanid { get; set; }
        public Nullable<decimal> remainpayment { get; set; }
        public string loanstatus { get; set; }
        public string status { get; set; }
    }
}
