//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_setting_email_phone
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<bool> mobile { get; set; }
        public Nullable<bool> email { get; set; }
    }
}
