//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSilder
    {
        public long SilderId { get; set; }
        public string SilderType { get; set; }
        public string ImageHeading { get; set; }
        public string Content { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
    }
}
