//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoiList
    {
        public int idno { get; set; }
        public string Refnumber { get; set; }
        public Nullable<System.DateTime> Insertdate { get; set; }
        public string Customername { get; set; }
        public string pickupaddress { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string WorkMode { get; set; }
        public Nullable<decimal> Cashlimit { get; set; }
        public string Depositionmode { get; set; }
        public string AdditionalRequirement { get; set; }
        public Nullable<int> Stateid { get; set; }
        public Nullable<int> Districtid { get; set; }
        public string CityName { get; set; }
        public string ClientName { get; set; }
        public string PointMobile { get; set; }
        public string PointName { get; set; }
        public string DCCode { get; set; }
        public string SubDescrtion { get; set; }
        public string Status { get; set; }
        public string Retailerid { get; set; }
        public string Requestid { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}
