//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manatorypermision
    {
        public int idno { get; set; }
        public string skips { get; set; }
        public string gst { get; set; }
        public string agreement { get; set; }
        public string addressproof { get; set; }
    }
}
