//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manual_opt_sts
    {
        public int id { get; set; }
        public string @operator { get; set; }
        public Nullable<decimal> minamount { get; set; }
        public string status { get; set; }
        public string respID { get; set; }
        public Nullable<decimal> maxamount { get; set; }
        public string portname { get; set; }
    }
}
