//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_details
    {
        public int idno { get; set; }
        public string msterid { get; set; }
        public string mastername { get; set; }
        public string Firm { get; set; }
        public int state { get; set; }
        public int distict { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string sts { get; set; }
        public string mobile { get; set; }
        public string slab_name { get; set; }
        public string email { get; set; }
        public string pancard { get; set; }
        public string adharcard { get; set; }
        public Nullable<int> pincode { get; set; }
        public string gst { get; set; }
        public string Photo { get; set; }
        public string CreatedBy { get; set; }
    }
}
