//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_DMT_NEW_COMM
    {
        public int idno { get; set; }
        public string MasterID { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> Comm { get; set; }
        public Nullable<bool> gst_sts { get; set; }
        public Nullable<bool> tds_sts { get; set; }
    }
}
