//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_top
    {
        public int idno { get; set; }
        public string users { get; set; }
        public string message { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string UserId { get; set; }
        public string Header { get; set; }
    }
}
