//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class microATM_merch_termi_Info
    {
        public int Idno { get; set; }
        public string Userid { get; set; }
        public string MerchantId { get; set; }
        public string TerminalId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string status { get; set; }
        public string m_id { get; set; }
        public string t_id { get; set; }
        public string MerchantSubmittionStatus { get; set; }
    }
}
