//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class microATM_MCC_CODE
    {
        public int Idno { get; set; }
        public string DESCRIPTION { get; set; }
        public string Credopay_MCC_CODE { get; set; }
        public string Credopay_MCC_CODE_Val { get; set; }
        public string Payswif_MCC_CODE { get; set; }
        public string Payswif_MCC_CODE_Val { get; set; }
    }
}
