//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIcroatm_admin_device_info
    {
        public int idno { get; set; }
        public string deviceid { get; set; }
        public Nullable<System.DateTime> inseteddate { get; set; }
        public string planname { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public string chargetype { get; set; }
    }
}
