//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Micro_atm_device_plan
    {
        public int idno { get; set; }
        public Nullable<decimal> deviceprice { get; set; }
        public Nullable<int> minquantity { get; set; }
        public Nullable<decimal> upto2 { get; set; }
        public Nullable<decimal> upto5 { get; set; }
        public Nullable<decimal> upto8 { get; set; }
        public Nullable<decimal> above8 { get; set; }
        public string planname { get; set; }
        public Nullable<int> noofdays { get; set; }
        public Nullable<decimal> dlm_upto2 { get; set; }
        public Nullable<decimal> dlm_upto5 { get; set; }
        public Nullable<decimal> dlm_upto8 { get; set; }
        public Nullable<decimal> dlm_above8 { get; set; }
        public Nullable<decimal> md_upto2 { get; set; }
        public Nullable<decimal> md_upto5 { get; set; }
        public Nullable<decimal> md_upto8 { get; set; }
        public Nullable<decimal> md_above8 { get; set; }
        public Nullable<decimal> monthly { get; set; }
        public Nullable<decimal> monthlydealer { get; set; }
        public Nullable<decimal> monthlymaster { get; set; }
    }
}
