//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Microatmcash_dlm_rem_comm
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<decimal> maxrs { get; set; }
        public Nullable<decimal> minvalue { get; set; }
    }
}
