//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicroAtm_Trans_info
    {
        public int idno { get; set; }
        public string retailerid { get; set; }
        public string Dealerid { get; set; }
        public string Masterid { get; set; }
        public string transaction_id { get; set; }
        public string rrn { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string merchant_id { get; set; }
        public string transaction_type { get; set; }
        public string tid { get; set; }
        public string payment_method { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string card_payment_type { get; set; }
        public string masked_pan { get; set; }
        public string response_description { get; set; }
        public string aggregator_id { get; set; }
        public string resp { get; set; }
        public Nullable<System.DateTime> transtime { get; set; }
        public Nullable<decimal> retailer_remain_pre { get; set; }
        public Nullable<decimal> Retailer_comm { get; set; }
        public Nullable<decimal> Retailer_gst { get; set; }
        public Nullable<decimal> Retailer_tds { get; set; }
        public Nullable<decimal> retailer_remain_post { get; set; }
        public Nullable<decimal> dealer_remain_pre { get; set; }
        public Nullable<decimal> dealer_comm { get; set; }
        public Nullable<decimal> dealer_gst { get; set; }
        public Nullable<decimal> dealer_tds { get; set; }
        public Nullable<decimal> dealer_remain_post { get; set; }
        public Nullable<decimal> master_remain_pre { get; set; }
        public Nullable<decimal> master_comm { get; set; }
        public Nullable<decimal> master_gst { get; set; }
        public Nullable<decimal> master_tds { get; set; }
        public Nullable<decimal> master_remain_post { get; set; }
        public Nullable<decimal> adminpre { get; set; }
        public Nullable<decimal> adminincome { get; set; }
        public Nullable<decimal> admingst { get; set; }
        public Nullable<decimal> admintds { get; set; }
        public Nullable<decimal> adminremainpost { get; set; }
        public string network { get; set; }
        public Nullable<System.DateTime> resptime { get; set; }
        public string Requestid { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public string card_usage_type { get; set; }
        public string IPaddress { get; set; }
        public string Devicetoken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ModelNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string InternetTYPE { get; set; }
        public string Address { get; set; }
    }
}
