//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPosInfo
    {
        public int Idno { get; set; }
        public string RetailerId { get; set; }
        public string Message { get; set; }
        public string transType { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string status { get; set; }
        public string merchantID { get; set; }
        public string bankmerchantID { get; set; }
        public string bankterminalID { get; set; }
        public string cardbrand { get; set; }
        public string cardholdername { get; set; }
        public string cardnumber { get; set; }
        public string cardtype { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string invoiceno { get; set; }
        public string paymentid { get; set; }
        public string merchantnameaddress { get; set; }
        public Nullable<decimal> AdminPre { get; set; }
        public Nullable<decimal> AdminPost { get; set; }
        public Nullable<decimal> MasterPre { get; set; }
        public Nullable<decimal> MasterPost { get; set; }
        public Nullable<decimal> DealerPre { get; set; }
        public Nullable<decimal> DealerPost { get; set; }
        public Nullable<decimal> RetailerPre { get; set; }
        public Nullable<decimal> RetailerPost { get; set; }
        public string mPOSid { get; set; }
        public Nullable<decimal> MdComm { get; set; }
        public Nullable<decimal> Dlm_Comm { get; set; }
        public Nullable<decimal> Rem_Comm { get; set; }
        public Nullable<decimal> mdgst { get; set; }
        public Nullable<decimal> dlmgst { get; set; }
        public Nullable<decimal> remgst { get; set; }
        public Nullable<decimal> mdincome { get; set; }
        public Nullable<decimal> dlmincome { get; set; }
        public Nullable<decimal> remincome { get; set; }
        public Nullable<decimal> adminincome { get; set; }
        public Nullable<decimal> purchase { get; set; }
        public string TxnId { get; set; }
        public string BankRRN { get; set; }
        public string reqid { get; set; }
        public Nullable<decimal> WhitelabelPre { get; set; }
        public Nullable<decimal> WhitelabelPost { get; set; }
        public Nullable<decimal> WhitelabelIncome { get; set; }
        public Nullable<decimal> WhitelabelGST { get; set; }
        public string IPaddress { get; set; }
        public string Devicetoken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ModelNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string InternetTYPE { get; set; }
        public string Address { get; set; }
    }
}
