//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtm_Comm_comm
    {
        public int idno { get; set; }
        public string users { get; set; }
        public Nullable<decimal> cash_0_1000_per { get; set; }
        public Nullable<decimal> cash_1001_2000_per { get; set; }
        public Nullable<decimal> mtm_500_1000_per { get; set; }
        public Nullable<decimal> mtm_1001_1499_per { get; set; }
        public Nullable<decimal> mtm_1500_1999_per { get; set; }
        public Nullable<decimal> mtm_2000_2499_per { get; set; }
        public Nullable<decimal> mtm_2500_2999_per { get; set; }
        public Nullable<decimal> mtm_3000_3499_per { get; set; }
        public Nullable<decimal> mtm_3500_5000_per { get; set; }
        public Nullable<decimal> mtm_5001_10000_per { get; set; }
        public Nullable<decimal> cash_0_1000_rs { get; set; }
        public Nullable<decimal> cash_1001_2000_rs { get; set; }
        public Nullable<decimal> mtm_500_1000_rs { get; set; }
        public Nullable<decimal> mtm_1001_1499_rs { get; set; }
        public Nullable<decimal> mtm_1500_1999_rs { get; set; }
        public Nullable<decimal> mtm_2000_2499_rs { get; set; }
        public Nullable<decimal> mtm_2500_2999_rs { get; set; }
        public Nullable<decimal> mtm_3000_3499_rs { get; set; }
        public Nullable<decimal> mtm_3500_5000_rs { get; set; }
        public Nullable<decimal> mtm_5001_10000_rs { get; set; }
        public Nullable<decimal> cash_0_1000_maxrs { get; set; }
        public Nullable<decimal> cash_1001_2000_maxrs { get; set; }
        public Nullable<decimal> mtm_500_1000_maxrs { get; set; }
        public Nullable<decimal> mtm_1001_1499_maxrs { get; set; }
        public Nullable<decimal> mtm_1500_1999_maxrs { get; set; }
        public Nullable<decimal> mtm_2000_2499_maxrs { get; set; }
        public Nullable<decimal> mtm_2500_2999_maxrs { get; set; }
        public Nullable<decimal> mtm_3000_3499_maxrs { get; set; }
        public Nullable<decimal> mtm_3500_5000_maxrs { get; set; }
        public Nullable<decimal> mtm_5001_10000_maxrs { get; set; }
        public string cash_0_1000_Type { get; set; }
        public string cash_1001_2000_Type { get; set; }
        public string mtm_500_1000_Type { get; set; }
        public string mtm_1001_1499_Type { get; set; }
        public string mtm_1500_1999_Type { get; set; }
        public string mtm_2000_2499_Type { get; set; }
        public string mtm_2500_2999_Type { get; set; }
        public string mtm_3000_3499_Type { get; set; }
        public string mtm_3500_5000_Type { get; set; }
        public string mtm_5001_10000_Type { get; set; }
    }
}
