//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nifipaymerchantinfo
    {
        public int idno { get; set; }
        public string Retailerid { get; set; }
        public string Merchantid { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> MerchantCreateDate { get; set; }
        public Nullable<System.DateTime> OTPVerifyDate { get; set; }
        public Nullable<System.DateTime> MerchantCompleteDate { get; set; }
        public string OtpverifyUniqueid { get; set; }
        public string KycUniqueid { get; set; }
    }
}
