//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NifiStatename
    {
        public int idno { get; set; }
        public Nullable<int> Stateid { get; set; }
        public string Name { get; set; }
        public string OrginalName { get; set; }
    }
}
