//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offerdetail
    {
        public decimal idno { get; set; }
        public string @operator { get; set; }
        public string Amountpre { get; set; }
        public string Amountpost { get; set; }
        public string secondkey { get; set; }
        public string thirdkey { get; set; }
    }
}
