//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer_details
    {
        public int id { get; set; }
        public string optcode { get; set; }
        public string port { get; set; }
        public string pre { get; set; }
        public string post { get; set; }
        public string number { get; set; }
        public string countpre { get; set; }
        public string spl { get; set; }
        public Nullable<int> lent { get; set; }
        public string countpost { get; set; }
    }
}
