//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operatorMerge
    {
        public int idno { get; set; }
        public string self_operator { get; set; }
        public string api_operator { get; set; }
        public string self_optcode { get; set; }
        public string api_optcode { get; set; }
    }
}
