//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operatorcommforsellStatu
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public string dlm_Name { get; set; }
        public string farmname { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Timing { get; set; }
        public string operator_1 { get; set; }
        public Nullable<decimal> comm { get; set; }
        public string status { get; set; }
    }
}
