//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidServicesPaymentHistory
    {
        public int Idno { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
        public string ServiceName { get; set; }
        public string PaymentType { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> RemainPre { get; set; }
        public Nullable<decimal> RemainPost { get; set; }
        public Nullable<decimal> AdminPre { get; set; }
        public Nullable<decimal> AdminPost { get; set; }
    }
}
