//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAN_CARD_API
    {
        public int IdNo { get; set; }
        public string Api_name { get; set; }
        public Nullable<decimal> Pan_purchase { get; set; }
        public Nullable<decimal> Pan_purchase_rs { get; set; }
        public Nullable<decimal> Pan_purchase_maxrs { get; set; }
        public string status { get; set; }
    }
}
