//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAN_CARD
    {
        public int Idno { get; set; }
        public string Acknowledgement { get; set; }
        public string Category { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Name_of_Card { get; set; }
        public string FFirstName { get; set; }
        public string FMiddleName { get; set; }
        public string FLastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string ISDCode { get; set; }
        public string STDCode { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string communicationAddress { get; set; }
        public string RA_Address { get; set; }
        public int State { get; set; }
        public int District { get; set; }
        public string ProofIdentity { get; set; }
        public string ProofAddress { get; set; }
        public string ProofDOB { get; set; }
        public decimal ProcessingFee { get; set; }
        public string RetailerId { get; set; }
        public string NameOnAadhaar { get; set; }
        public string Adhaar_EID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public string IsApproved { get; set; }
        public string DefencePersonnel { get; set; }
        public Nullable<System.DateTime> APR_DATE { get; set; }
        public string AreaCode { get; set; }
        public string AOTYPE { get; set; }
        public string RangeCode { get; set; }
        public string AONO { get; set; }
        public string ApplicantTitle { get; set; }
        public string MFirstName { get; set; }
        public string MMiddleName { get; set; }
        public string MLastName { get; set; }
        public string Parent { get; set; }
        public string Flat_Door_Block_No { get; set; }
        public string Premises_Building_Village { get; set; }
        public string Road_Street_Lane_Post { get; set; }
        public string Area_SubDivision { get; set; }
        public string PIN { get; set; }
        public string SourceOfIncome { get; set; }
        public string IsSalariedEmployee { get; set; }
        public string OrganisationName { get; set; }
        public string IsBussinessProfession { get; set; }
        public string BussinessProfessionCode { get; set; }
        public Nullable<System.DateTime> AadhaarDOB { get; set; }
        public string IsSignaturePresence { get; set; }
        public string NameofVerifier { get; set; }
        public string CapacityOfVerifier { get; set; }
        public string PlaceOfVerification { get; set; }
        public string IsKYCCompliant { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<System.DateTime> DocumentUpdateDate { get; set; }
        public string DocForm49FirstPage { get; set; }
        public string Docs { get; set; }
        public string AdhaarNo { get; set; }
        public string AdhaarGender { get; set; }
        public Nullable<bool> IsDocUploaded { get; set; }
        public string PAN_CARD_NO { get; set; }
        public Nullable<bool> IsDocAccepted { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
        public Nullable<bool> IsHidden { get; set; }
    }
}
