//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAN_CARD_Purchase
    {
        public int Idno { get; set; }
        public string API_NAME { get; set; }
        public Nullable<decimal> PurchaseInRs { get; set; }
        public System.DateTime Date { get; set; }
    }
}
