//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pancard_transation_manual
    {
        public int idno { get; set; }
        public string Reailerid { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public string Aadharno { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string AadharregNumber { get; set; }
        public string Fathername { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Rem_comm { get; set; }
        public Nullable<decimal> Rem_tds { get; set; }
        public Nullable<decimal> Rem_pre { get; set; }
        public Nullable<decimal> rem_post { get; set; }
        public Nullable<decimal> Rem_final { get; set; }
        public string dealer_id { get; set; }
        public Nullable<decimal> dlm_comm { get; set; }
        public Nullable<decimal> dlm_tds { get; set; }
        public Nullable<decimal> dlm_pre { get; set; }
        public Nullable<decimal> dlm_post { get; set; }
        public Nullable<decimal> dlm_final { get; set; }
        public string master_id { get; set; }
        public Nullable<decimal> master_comm { get; set; }
        public Nullable<decimal> master_tds { get; set; }
        public Nullable<decimal> master_pre { get; set; }
        public Nullable<decimal> master_post { get; set; }
        public Nullable<decimal> master_final { get; set; }
        public string status { get; set; }
        public string requestid { get; set; }
        public Nullable<System.DateTime> request_time { get; set; }
        public Nullable<System.DateTime> responce_time { get; set; }
        public string imageurl { get; set; }
        public string State { get; set; }
    }
}
