//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pancard_whitelabel_CommonAll_comm
    {
        public int idno { get; set; }
        public string whitelabelid { get; set; }
        public Nullable<decimal> tokenvalueDigital { get; set; }
        public Nullable<decimal> tokenvaluePhysical { get; set; }
        public Nullable<decimal> dealerDigital { get; set; }
        public Nullable<decimal> dealerPhysical { get; set; }
        public Nullable<decimal> retailerDigital { get; set; }
        public Nullable<decimal> retailerPhysical { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> Purchase { get; set; }
        public Nullable<decimal> masterdigital { get; set; }
        public Nullable<decimal> masterphysical { get; set; }
        public Nullable<decimal> PurchaseDigital { get; set; }
        public Nullable<decimal> PurchasePhysical { get; set; }
        public Nullable<decimal> dlmremvaluephysical { get; set; }
        public Nullable<decimal> dlmremvaluedigital { get; set; }
    }
}
