//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pancard_distributor_Common_comm
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> tokenvalueDigital { get; set; }
        public Nullable<decimal> tokenvaluePhysical { get; set; }
        public Nullable<decimal> commDigital { get; set; }
        public Nullable<decimal> commPhysical { get; set; }
        public Nullable<decimal> gst { get; set; }
    }
}
