//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pancard_Common_comm
    {
        public int idno { get; set; }
        public Nullable<decimal> tokenvalueDigital { get; set; }
        public Nullable<decimal> tokenvaluePhysical { get; set; }
        public Nullable<decimal> masterDigital { get; set; }
        public Nullable<decimal> masterPhysical { get; set; }
        public Nullable<decimal> DistributorDigital { get; set; }
        public Nullable<decimal> DistributorPhysical { get; set; }
        public Nullable<decimal> RetailerDigital { get; set; }
        public Nullable<decimal> RetailerPhysical { get; set; }
        public Nullable<decimal> WhitelabelDigital { get; set; }
        public Nullable<decimal> WhitelabelPhysical { get; set; }
        public Nullable<decimal> ApiDigital { get; set; }
        public Nullable<decimal> ApiPhysical { get; set; }
        public Nullable<decimal> PurchaseDigital { get; set; }
        public Nullable<decimal> PurchasePhysical { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> dlmremvaluephysical { get; set; }
        public Nullable<decimal> dlmremvaluedigital { get; set; }
    }
}
