//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pancard_common_comm_new_manual
    {
        public int idno { get; set; }
        public Nullable<decimal> retailer_comm { get; set; }
        public Nullable<decimal> dealer_comm { get; set; }
        public Nullable<decimal> master_comm { get; set; }
    }
}
