//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGatewaycharge_new
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<bool> CreditCardsts { get; set; }
        public Nullable<bool> DebitCardsts { get; set; }
        public Nullable<bool> netbankingsts { get; set; }
        public Nullable<bool> cashcardsts { get; set; }
        public Nullable<bool> walletsts { get; set; }
        public Nullable<decimal> debitupto2000 { get; set; }
        public Nullable<decimal> debitabove2000 { get; set; }
        public Nullable<decimal> rupaydebit { get; set; }
        public Nullable<decimal> creditcard { get; set; }
        public Nullable<decimal> netbanking { get; set; }
        public Nullable<decimal> amex { get; set; }
        public Nullable<decimal> internationalcard { get; set; }
        public Nullable<decimal> wallet { get; set; }
        public Nullable<decimal> UPI { get; set; }
        public Nullable<decimal> prepaidcard { get; set; }
        public Nullable<decimal> creditcardmin { get; set; }
        public Nullable<decimal> creditcardmax { get; set; }
        public Nullable<decimal> netbankmin { get; set; }
        public Nullable<decimal> netbankmax { get; set; }
        public Nullable<decimal> debitmin { get; set; }
        public Nullable<decimal> debitmax { get; set; }
        public Nullable<decimal> walletmin { get; set; }
        public Nullable<decimal> walletmax { get; set; }
        public Nullable<decimal> axis { get; set; }
        public Nullable<decimal> others { get; set; }
        public Nullable<bool> upists { get; set; }
        public Nullable<decimal> upimin { get; set; }
        public Nullable<decimal> upimax { get; set; }
        public string creditsettlement { get; set; }
    }
}
