//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paytm_imps_dlm_rem_comm1
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> verify_comm { get; set; }
        public Nullable<decimal> comm_1000 { get; set; }
        public Nullable<decimal> comm_2000 { get; set; }
        public Nullable<decimal> comm_3000 { get; set; }
        public Nullable<decimal> comm_4000 { get; set; }
        public Nullable<decimal> comm_5000 { get; set; }
        public Nullable<decimal> comm_6000 { get; set; }
        public Nullable<decimal> comm_7000 { get; set; }
        public Nullable<decimal> comm_8000 { get; set; }
        public Nullable<decimal> comm_9000 { get; set; }
        public Nullable<decimal> comm_10000 { get; set; }
        public Nullable<decimal> comm_11000 { get; set; }
        public Nullable<decimal> comm_12000 { get; set; }
        public Nullable<decimal> comm_13000 { get; set; }
        public Nullable<decimal> comm_14000 { get; set; }
        public Nullable<decimal> comm_15000 { get; set; }
        public Nullable<decimal> comm_16000 { get; set; }
        public Nullable<decimal> comm_17000 { get; set; }
        public Nullable<decimal> comm_18000 { get; set; }
        public Nullable<decimal> comm_19000 { get; set; }
        public Nullable<decimal> comm_20000 { get; set; }
        public Nullable<decimal> comm_21000 { get; set; }
        public Nullable<decimal> comm_22000 { get; set; }
        public Nullable<decimal> comm_23000 { get; set; }
        public Nullable<decimal> comm_24000 { get; set; }
        public Nullable<decimal> comm_25000 { get; set; }
        public Nullable<decimal> comm_26000 { get; set; }
        public Nullable<decimal> comm_27000 { get; set; }
        public Nullable<decimal> comm_28000 { get; set; }
        public Nullable<decimal> comm_29000 { get; set; }
        public Nullable<decimal> comm_30000 { get; set; }
        public Nullable<decimal> comm_31000 { get; set; }
        public Nullable<decimal> comm_32000 { get; set; }
        public Nullable<decimal> comm_33000 { get; set; }
        public Nullable<decimal> comm_34000 { get; set; }
        public Nullable<decimal> comm_35000 { get; set; }
        public Nullable<decimal> comm_36000 { get; set; }
        public Nullable<decimal> comm_37000 { get; set; }
        public Nullable<decimal> comm_38000 { get; set; }
        public Nullable<decimal> comm_39000 { get; set; }
        public Nullable<decimal> comm_40000 { get; set; }
        public Nullable<decimal> comm_41000 { get; set; }
        public Nullable<decimal> comm_42000 { get; set; }
        public Nullable<decimal> comm_43000 { get; set; }
        public Nullable<decimal> comm_44000 { get; set; }
        public Nullable<decimal> comm_45000 { get; set; }
        public Nullable<decimal> comm_46000 { get; set; }
        public Nullable<decimal> comm_47000 { get; set; }
        public Nullable<decimal> comm_48000 { get; set; }
        public Nullable<decimal> comm_49000 { get; set; }
        public Nullable<decimal> comm_50000 { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<bool> gst_sts { get; set; }
        public Nullable<bool> tds_sts { get; set; }
        public Nullable<decimal> per_26000 { get; set; }
        public Nullable<decimal> maxrs_26000 { get; set; }
        public string Type_26000 { get; set; }
        public string Type_1000 { get; set; }
        public string Type_2000 { get; set; }
        public string Type_3000 { get; set; }
        public string Type_4000 { get; set; }
        public string Type_5000 { get; set; }
        public string Type_6000 { get; set; }
        public string Type_7000 { get; set; }
        public string Type_8000 { get; set; }
        public string Type_9000 { get; set; }
        public string Type_10000 { get; set; }
        public string Type_11000 { get; set; }
        public string Type_12000 { get; set; }
        public string Type_13000 { get; set; }
        public string Type_14000 { get; set; }
        public string Type_15000 { get; set; }
        public string Type_16000 { get; set; }
        public string Type_17000 { get; set; }
        public string Type_18000 { get; set; }
        public string Type_19000 { get; set; }
        public string Type_20000 { get; set; }
        public string Type_21000 { get; set; }
        public string Type_22000 { get; set; }
        public string Type_23000 { get; set; }
        public string Type_24000 { get; set; }
        public string Type_25000 { get; set; }
    }
}
