//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYU_QR_info
    {
        public int idno { get; set; }
        public string ApiRequest { get; set; }
        public string ApiResponse { get; set; }
        public string Uniqueid { get; set; }
        public string VPAID { get; set; }
        public string userid { get; set; }
        public string role { get; set; }
        public string QRCODE { get; set; }
        public string QRID { get; set; }
    }
}
