//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phonepaygatewayinfo
    {
        public int idno { get; set; }
        public string XCsrfToken { get; set; }
        public string CKB2N1BHVZ { get; set; }
        public string OCULUS_G_TOKEN { get; set; }
        public string Fingerprint { get; set; }
        public string upiid { get; set; }
    }
}
