//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phonepeauth
    {
        public int id { get; set; }
        public string merchantid { get; set; }
        public string secretkey { get; set; }
        public string key1 { get; set; }
    }
}
