//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortManager
    {
        public string PortNo { get; set; }
        public string ReadPort { get; set; }
        public string WritePort { get; set; }
        public string SMS { get; set; }
        public string Operator { get; set; }
        public string Active { get; set; }
        public string Multiple { get; set; }
        public string Method { get; set; }
        public string powerOnOff { get; set; }
        public string Ready { get; set; }
        public string Signal { get; set; }
        public string Bal { get; set; }
        public string Pin { get; set; }
        public string Status { get; set; }
        public string Sname { get; set; }
        public string mType { get; set; }
        public string Lapuno { get; set; }
        public Nullable<System.DateTime> olddt { get; set; }
        public string AC { get; set; }
        public string PortNm { get; set; }
        public string codes { get; set; }
        public string machinename { get; set; }
        public string name { get; set; }
        public string phonenumber { get; set; }
        public int idno { get; set; }
    }
}
