//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPI_Master_comm_new
    {
        public int idno { get; set; }
        public string Userid { get; set; }
        public Nullable<decimal> Comm_1000 { get; set; }
        public Nullable<decimal> Comm_2000 { get; set; }
        public Nullable<decimal> Comm_3000 { get; set; }
        public Nullable<decimal> Comm_4000 { get; set; }
        public Nullable<decimal> Comm_5000 { get; set; }
        public Nullable<decimal> Comm_6000 { get; set; }
        public Nullable<decimal> Comm_7000 { get; set; }
        public Nullable<decimal> Comm_8000 { get; set; }
        public Nullable<decimal> Comm_9000 { get; set; }
        public Nullable<decimal> Comm_10000 { get; set; }
        public Nullable<decimal> Comm_11000 { get; set; }
        public Nullable<decimal> Comm_12000 { get; set; }
        public Nullable<decimal> Comm_13000 { get; set; }
        public Nullable<decimal> Comm_14000 { get; set; }
        public Nullable<decimal> Comm_15000 { get; set; }
        public Nullable<decimal> Comm_16000 { get; set; }
        public Nullable<decimal> Comm_17000 { get; set; }
        public Nullable<decimal> Comm_18000 { get; set; }
        public Nullable<decimal> Comm_19000 { get; set; }
        public Nullable<decimal> Comm_20000 { get; set; }
        public Nullable<decimal> Comm_21000 { get; set; }
        public Nullable<decimal> Comm_22000 { get; set; }
        public Nullable<decimal> Comm_23000 { get; set; }
        public Nullable<decimal> Comm_24000 { get; set; }
        public Nullable<decimal> Comm_25000 { get; set; }
        public Nullable<decimal> verifycomm { get; set; }
    }
}
