//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPI_common_comm_new
    {
        public int idno { get; set; }
        public string usertype { get; set; }
        public Nullable<decimal> VerifyComm { get; set; }
        public Nullable<decimal> Comm_1000 { get; set; }
        public Nullable<decimal> Comm_1000_Charge { get; set; }
        public Nullable<decimal> Comm_2000 { get; set; }
        public Nullable<decimal> Comm_2000_Charge { get; set; }
        public Nullable<decimal> Comm_3000 { get; set; }
        public Nullable<decimal> Comm_3000_Charge { get; set; }
        public Nullable<decimal> Comm_4000 { get; set; }
        public Nullable<decimal> Comm_4000_Charge { get; set; }
        public Nullable<decimal> Comm_5000 { get; set; }
        public Nullable<decimal> Comm_5000_Charge { get; set; }
        public Nullable<decimal> Comm_6000 { get; set; }
        public Nullable<decimal> Comm_6000_Charge { get; set; }
        public Nullable<decimal> Comm_7000 { get; set; }
        public Nullable<decimal> Comm_7000_Charge { get; set; }
        public Nullable<decimal> Comm_8000 { get; set; }
        public Nullable<decimal> Comm_8000_Charge { get; set; }
        public Nullable<decimal> Comm_9000 { get; set; }
        public Nullable<decimal> Comm_9000_Charge { get; set; }
        public Nullable<decimal> Comm_10000 { get; set; }
        public Nullable<decimal> Comm_10000_Charge { get; set; }
        public Nullable<decimal> Comm_11000 { get; set; }
        public Nullable<decimal> Comm_11000_Charge { get; set; }
        public Nullable<decimal> Comm_12000 { get; set; }
        public Nullable<decimal> Comm_12000_Charge { get; set; }
        public Nullable<decimal> Comm_13000 { get; set; }
        public Nullable<decimal> Comm_13000_Charge { get; set; }
        public Nullable<decimal> Comm_14000 { get; set; }
        public Nullable<decimal> Comm_14000_Charge { get; set; }
        public Nullable<decimal> Comm_15000 { get; set; }
        public Nullable<decimal> Comm_15000_Charge { get; set; }
        public Nullable<decimal> Comm_16000 { get; set; }
        public Nullable<decimal> Comm_16000_Charge { get; set; }
        public Nullable<decimal> Comm_17000 { get; set; }
        public Nullable<decimal> Comm_17000_Charge { get; set; }
        public Nullable<decimal> Comm_18000 { get; set; }
        public Nullable<decimal> Comm_18000_Charge { get; set; }
        public Nullable<decimal> Comm_19000 { get; set; }
        public Nullable<decimal> Comm_20000 { get; set; }
        public Nullable<decimal> Comm_20000_Charge { get; set; }
        public Nullable<decimal> Comm_21000 { get; set; }
        public Nullable<decimal> Comm_21000_Charge { get; set; }
        public Nullable<decimal> Comm_22000 { get; set; }
        public Nullable<decimal> Comm_22000_Charge { get; set; }
        public Nullable<decimal> Comm_23000 { get; set; }
        public Nullable<decimal> Comm_23000_Charge { get; set; }
        public Nullable<decimal> Comm_24000 { get; set; }
        public Nullable<decimal> Comm_24000_Charge { get; set; }
        public Nullable<decimal> Comm_25000 { get; set; }
        public Nullable<decimal> Comm_25000_Charge { get; set; }
        public Nullable<decimal> Comm_19000_Charge { get; set; }
    }
}
