//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prepaid_dealer_common_comm
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public string optcode { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<decimal> comm1 { get; set; }
        public Nullable<decimal> comm2 { get; set; }
    }
}
