//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prepaid_common_comm
    {
        public int idno { get; set; }
        public string optcode { get; set; }
        public Nullable<decimal> mastercomm { get; set; }
        public Nullable<decimal> dlmcomm { get; set; }
        public Nullable<decimal> retailercomm { get; set; }
        public Nullable<decimal> whitelabelcomm { get; set; }
        public Nullable<decimal> apicomm { get; set; }
        public Nullable<decimal> dlm_rem_comm { get; set; }
        public Nullable<decimal> mastercomm1 { get; set; }
        public Nullable<decimal> mastercomm2 { get; set; }
        public Nullable<decimal> dlmcomm1 { get; set; }
        public Nullable<decimal> dlmcomm2 { get; set; }
        public Nullable<decimal> dlm_rem_comm1 { get; set; }
        public Nullable<decimal> dlm_rem_comm2 { get; set; }
        public Nullable<decimal> apicomm1 { get; set; }
        public Nullable<decimal> apicomm2 { get; set; }
        public Nullable<decimal> whitelabelcomm1 { get; set; }
        public Nullable<decimal> whitelabelcomm2 { get; set; }
    }
}
