//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prepaid_card_Transaction
    {
        public int idno { get; set; }
        public string REtailerid { get; set; }
        public string Name { get; set; }
        public string mobile { get; set; }
        public string Email { get; set; }
        public string DOB { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Request_time { get; set; }
        public Nullable<System.DateTime> Response_time { get; set; }
        public string Request_id { get; set; }
        public Nullable<decimal> Rem_remain_pre { get; set; }
        public Nullable<decimal> Rem_comm { get; set; }
        public Nullable<decimal> rem_gst { get; set; }
        public Nullable<decimal> rem_tds { get; set; }
        public Nullable<decimal> rem_remain_post { get; set; }
        public Nullable<decimal> rem_final { get; set; }
        public string dlm_id { get; set; }
        public Nullable<decimal> dlm_pre { get; set; }
        public Nullable<decimal> dlm_comm { get; set; }
        public Nullable<decimal> dlm_gst { get; set; }
        public Nullable<decimal> dlm_tds { get; set; }
        public Nullable<decimal> dlm_remain_post { get; set; }
        public Nullable<decimal> dlm_final { get; set; }
        public string master_id { get; set; }
        public Nullable<decimal> master_pre { get; set; }
        public Nullable<decimal> master_comm { get; set; }
        public Nullable<decimal> master_gst { get; set; }
        public Nullable<decimal> master_tds { get; set; }
        public Nullable<decimal> master_remain_post { get; set; }
        public Nullable<decimal> master_final { get; set; }
    }
}
