//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer_paperSize_Changes
    {
        public int idno { get; set; }
        public string Userid { get; set; }
        public string Print_Name { get; set; }
        public string status { get; set; }
    }
}
