//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVendor
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string VenderID { get; set; }
        public decimal StandardPrice { get; set; }
        public decimal ListPrice { get; set; }
        public int MinOrderQty { get; set; }
        public int MaxOrderQty { get; set; }
        public int OnOrderQty { get; set; }
        public decimal AdminComm { get; set; }
        public decimal MDComm { get; set; }
        public decimal DEComm { get; set; }
        public decimal RemComm { get; set; }
        public decimal WhiteLabelComm { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
