//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purcharge_bal
    {
        public int idno { get; set; }
        public string portno { get; set; }
        public string imeino { get; set; }
        public string simname { get; set; }
        public Nullable<decimal> purcharge { get; set; }
        public Nullable<System.DateTime> gdate { get; set; }
        public string mobno { get; set; }
    }
}
