//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Account_info
    {
        public int idno { get; set; }
        public string APINAME { get; set; }
        public string Payeename { get; set; }
        public string AccountNo { get; set; }
        public string Ifsccode { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public string bankname { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    }
}
