//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDealerToken
    {
        public int idno { get; set; }
        public string DealerId { get; set; }
        public Nullable<decimal> DealerPre { get; set; }
        public Nullable<decimal> DealerPost { get; set; }
        public Nullable<decimal> AdminPre { get; set; }
        public Nullable<decimal> AdminPost { get; set; }
        public Nullable<decimal> TotalTokenValue { get; set; }
        public Nullable<decimal> TotalDebit { get; set; }
        public string TotalToken { get; set; }
        public string PerTokenValue { get; set; }
    }
}
