//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiantTransfer
    {
        public int idno { get; set; }
        public string Userid { get; set; }
        public string CEID { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> Remainpre { get; set; }
        public Nullable<decimal> Remainpost { get; set; }
        public Nullable<System.DateTime> Insertdate { get; set; }
        public Nullable<System.DateTime> Responsedate { get; set; }
        public string Sts { get; set; }
        public Nullable<decimal> Adminremainpre { get; set; }
        public Nullable<decimal> Adminremainpost { get; set; }
        public string RequestID { get; set; }
    }
}
