//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiantPrepayTransfer
    {
        public int idno { get; set; }
        public string Userid { get; set; }
        public string CEID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RemainPre { get; set; }
        public Nullable<decimal> RemainPost { get; set; }
        public Nullable<System.DateTime> Insertdate { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public string sts { get; set; }
        public Nullable<decimal> Adminremainpre { get; set; }
        public Nullable<decimal> Adminremainpost { get; set; }
        public string RequestID { get; set; }
        public string Clientname { get; set; }
        public string Shop_id { get; set; }
        public string transid { get; set; }
    }
}
