//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiantCashDeposite
    {
        public int Idno { get; set; }
        public string Userid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Remainpre { get; set; }
        public Nullable<decimal> Remainpost { get; set; }
        public Nullable<decimal> Adminremainpre { get; set; }
        public Nullable<decimal> Adminremainpost { get; set; }
        public Nullable<System.DateTime> Insertdate { get; set; }
        public System.DateTime Updatedate { get; set; }
        public string Status { get; set; }
        public string BankName { get; set; }
        public string Ifsccode { get; set; }
        public string Accountnumber { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<decimal> FinalCharge { get; set; }
        public Nullable<decimal> Gst { get; set; }
        public Nullable<decimal> Tds { get; set; }
        public string Mode { get; set; }
        public string Slipid { get; set; }
        public string Slipname { get; set; }
        public string RejectedReson { get; set; }
        public string ResponseBy { get; set; }
        public string Requestid { get; set; }
    }
}
