//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rang_of_imps_transaction_dealer
    {
        public int idno { get; set; }
        public string Dealer_id { get; set; }
        public Nullable<int> vastbazzar_min { get; set; }
        public Nullable<int> vastbazzar_max { get; set; }
        public Nullable<int> instatntpay_min { get; set; }
        public Nullable<int> instatntpay_max { get; set; }
        public Nullable<int> Razorpay_min { get; set; }
        public Nullable<int> razorpay_max { get; set; }
    }
}
