//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Range_wise_extra_commission
    {
        public int idno { get; set; }
        public string opratoridid { get; set; }
        public Nullable<decimal> minamount { get; set; }
        public Nullable<decimal> maxamnt { get; set; }
        public Nullable<decimal> Com_in_per { get; set; }
        public Nullable<bool> statuss { get; set; }
        public Nullable<System.DateTime> last_status_changedate { get; set; }
    }
}
