//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCH_Details
    {
        public string SSId { get; set; }
        public string RCHId { get; set; }
        public string RCHName { get; set; }
        public Nullable<System.DateTime> DOF { get; set; }
        public string FarmName { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Photo { get; set; }
        public string Status { get; set; }
        public string portname { get; set; }
        public string pancard { get; set; }
        public string adharcard { get; set; }
    }
}
