//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge_info
    {
        public int idno { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string optcode { get; set; }
        public string Rstaus { get; set; }
        public Nullable<System.DateTime> Rch_time { get; set; }
        public Nullable<System.DateTime> Resp_time { get; set; }
        public string Rch_from { get; set; }
        public Nullable<decimal> Remain { get; set; }
        public Nullable<decimal> whitelabelremain { get; set; }
        public Nullable<decimal> masterremain { get; set; }
        public Nullable<decimal> dealerremain { get; set; }
        public string portno { get; set; }
        public string rch_type { get; set; }
        public string OPt_id { get; set; }
        public Nullable<decimal> lapu_bal { get; set; }
        public string Recharge_request { get; set; }
        public string Recharge_response { get; set; }
        public string API_Request { get; set; }
        public string API_response { get; set; }
        public string Order_id { get; set; }
        public Nullable<decimal> purchase { get; set; }
        public Nullable<decimal> income { get; set; }
        public Nullable<decimal> whitelabelincome { get; set; }
        public Nullable<decimal> masterincome { get; set; }
        public Nullable<decimal> dealerincome { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string imeino { get; set; }
        public string lapuno { get; set; }
        public string lapuinfo { get; set; }
        public string Api_Response_output { get; set; }
        public string response_output { get; set; }
        public Nullable<decimal> Cashback { get; set; }
        public string optional1 { get; set; }
        public string optional2 { get; set; }
        public string optional3 { get; set; }
        public string optional4 { get; set; }
        public string refid { get; set; }
        public Nullable<decimal> user_remain_pre { get; set; }
        public Nullable<decimal> whitelabel_remain_pre { get; set; }
        public Nullable<decimal> master_remain_pre { get; set; }
        public Nullable<decimal> dealer_remain_pre { get; set; }
        public Nullable<decimal> adminincome { get; set; }
        public Nullable<decimal> user_gst { get; set; }
        public Nullable<decimal> dealer_gst { get; set; }
        public Nullable<decimal> master_gst { get; set; }
        public Nullable<decimal> whitelabel_gst { get; set; }
        public Nullable<decimal> user_comm { get; set; }
        public Nullable<decimal> master_comm { get; set; }
        public Nullable<decimal> dealer_comm { get; set; }
        public Nullable<decimal> whitelabel_comm { get; set; }
        public Nullable<decimal> Retailer_Surcharge { get; set; }
        public Nullable<decimal> Retailer_Tds { get; set; }
        public Nullable<decimal> Master_Tds { get; set; }
        public Nullable<decimal> Dealer_Tds { get; set; }
        public Nullable<decimal> Admin_Tds { get; set; }
        public Nullable<decimal> Admin_Gst { get; set; }
        public Nullable<decimal> servicefee { get; set; }
        public string backupchk { get; set; }
        public string Devicetoken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ModelNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string InternetTYPE { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> RemExtracomm { get; set; }
        public string MdCommhold { get; set; }
        public Nullable<System.DateTime> holddatemd { get; set; }
        public string dlmCommhold { get; set; }
        public Nullable<System.DateTime> holddatedlm { get; set; }
        public string BillDueDate { get; set; }
        public string prepaidtype { get; set; }
        public string Circle { get; set; }
        public Nullable<decimal> exclusive_gst { get; set; }
    }
}
