//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rechargeapirespons
    {
        public int Idno { get; set; }
        public int id { get; set; }
        public string Resptype { get; set; }
        public string KeyRequestid { get; set; }
        public string KeyStatus { get; set; }
        public string KeyOptID { get; set; }
        public string KeyMsg { get; set; }
        public string KeyRemainBal { get; set; }
        public string ValStatusSucess { get; set; }
        public string ValStatusFailed { get; set; }
        public string ValStatusPending { get; set; }
        public string sapratewith { get; set; }
        public string Keyerror { get; set; }
        public string KeyerrorMessage { get; set; }
        public string valerror { get; set; }
        public string valerrorMessage { get; set; }
        public string ip_address { get; set; }
        public string update_time { get; set; }
    
        public virtual RechargeapiInfo RechargeapiInfo { get; set; }
    }
}
