//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge_Amount_range
    {
        public int idno { get; set; }
        public Nullable<decimal> maximum1 { get; set; }
        public Nullable<decimal> maximum2 { get; set; }
    }
}
