//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge_excelupload_data
    {
        public int idno { get; set; }
        public string Rch_no { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string optname { get; set; }
        public string op1 { get; set; }
        public string op2 { get; set; }
        public string op3 { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string Status { get; set; }
        public string Req { get; set; }
        public string Resp { get; set; }
        public string rch_sts { get; set; }
        public string Userid { get; set; }
        public Nullable<System.DateTime> proceeddate { get; set; }
        public string Reason { get; set; }
    }
}
