//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge_API_URLS
    {
        public int Idno { get; set; }
        public string API_Name { get; set; }
        public string Status { get; set; }
        public string API_ID { get; set; }
        public string Api_pwd { get; set; }
        public string Token { get; set; }
        public string url { get; set; }
        public string token1 { get; set; }
        public string token2 { get; set; }
        public string token3 { get; set; }
        public string prioritytoken { get; set; }
    }
}
