//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge_sell_by_dealer
    {
        public int idno { get; set; }
        public string Dealerid { get; set; }
        public Nullable<System.DateTime> datetimes { get; set; }
        public Nullable<bool> registration_Status { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
