//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeStatusCheck
    {
        public int id { get; set; }
        public string apiname { get; set; }
        public string url { get; set; }
        public string method_type { get; set; }
        public string body { get; set; }
        public string userid_key { get; set; }
        public string requestid_key { get; set; }
        public string tokenId_key { get; set; }
        public string userid_value { get; set; }
        public string requestid_value { get; set; }
        public string tokenId_value { get; set; }
        public string response_type { get; set; }
        public string status_key { get; set; }
        public string operatorid_key { get; set; }
        public string status_success_value { get; set; }
        public string status_failed_value { get; set; }
        public string operatorid_value { get; set; }
        public string separated_by { get; set; }
    }
}
