//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recharge_switch
    {
        public int idno { get; set; }
        public string Recharge_from { get; set; }
        public string Type { get; set; }
        public string sts { get; set; }
        public string opt { get; set; }
        public string users { get; set; }
        public string portno { get; set; }
    }
}
