//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge_info_Failed_TO_Success_Reports
    {
        public int idno { get; set; }
        public Nullable<int> rchidno { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string optcode { get; set; }
        public string modifystaus { get; set; }
        public Nullable<System.DateTime> Rch_time { get; set; }
        public Nullable<System.DateTime> Resp_time { get; set; }
        public Nullable<System.DateTime> Modify_time { get; set; }
        public string Rch_from { get; set; }
        public string portno { get; set; }
        public string rch_type { get; set; }
        public string OPt_id { get; set; }
        public string Order_id { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string imeino { get; set; }
        public string lapuno { get; set; }
        public string lapuinfo { get; set; }
        public string Api_Response_output { get; set; }
        public string response_output { get; set; }
        public string optional1 { get; set; }
        public string optional2 { get; set; }
        public string optional3 { get; set; }
        public string optional4 { get; set; }
        public string refid { get; set; }
        public string backupchk { get; set; }
        public string Devicetoken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ModelNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string InternetTYPE { get; set; }
        public string Address { get; set; }
        public Nullable<bool> ISREAD { get; set; }
    }
}
