//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeapiInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RechargeapiInfo()
        {
            this.ApiCallBackURLs = new HashSet<ApiCallBackURL>();
            this.rechargeapiresponses = new HashSet<rechargeapirespons>();
        }
    
        public int id { get; set; }
        public string apitype { get; set; }
        public string Requesttype { get; set; }
        public string apiname { get; set; }
        public string apiendpoint { get; set; }
        public bool Sts { get; set; }
        public string RandomName { get; set; }
        public string Apiid { get; set; }
        public string Keyuserid { get; set; }
        public string Keypasscode { get; set; }
        public string Keyrechargeno { get; set; }
        public string Keyoptcode { get; set; }
        public string KeyAmount { get; set; }
        public string KeyReqid { get; set; }
        public string valuserid { get; set; }
        public string valpasscode { get; set; }
        public string isstv { get; set; }
        public string keystatecode { get; set; }
        public string keynoromaing { get; set; }
        public Nullable<bool> success_to_failed { get; set; }
        public Nullable<bool> failed_to_success { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiCallBackURL> ApiCallBackURLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rechargeapirespons> rechargeapiresponses { get; set; }
    }
}
