//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referalcode_benifit_History
    {
        public int idno { get; set; }
        public string Whitelabelid { get; set; }
        public string Retailerid { get; set; }
        public Nullable<decimal> Refamount { get; set; }
        public Nullable<decimal> Rempre { get; set; }
        public Nullable<decimal> rempost { get; set; }
        public Nullable<decimal> whiteremainpre { get; set; }
        public Nullable<decimal> whiteremainpost { get; set; }
        public Nullable<System.DateTime> refdate { get; set; }
        public string usedrefcode { get; set; }
        public string assignrefcode { get; set; }
    }
}
