//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rem_IRCTC_Txninfo
    {
        public int idno { get; set; }
        public string remid { get; set; }
        public string remmobile { get; set; }
        public string remEmail { get; set; }
        public string secondmobile { get; set; }
        public string secondemail { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> txn_date { get; set; }
        public Nullable<System.DateTime> response_time { get; set; }
        public Nullable<System.DateTime> expire_time { get; set; }
        public Nullable<decimal> remain { get; set; }
        public Nullable<decimal> whitelabelremain { get; set; }
        public Nullable<decimal> masterremain { get; set; }
        public Nullable<decimal> dealerremain { get; set; }
        public Nullable<decimal> adminremain { get; set; }
        public string device_type { get; set; }
        public string TxnID { get; set; }
        public Nullable<decimal> remain_pre { get; set; }
        public Nullable<decimal> whitelabel_remain_pre { get; set; }
        public Nullable<decimal> master_remain_pre { get; set; }
        public Nullable<decimal> dealer_remain_pre { get; set; }
        public Nullable<decimal> admin_remain_pre { get; set; }
        public Nullable<decimal> master_comm { get; set; }
        public Nullable<decimal> dealer_comm { get; set; }
        public Nullable<decimal> master_income { get; set; }
        public Nullable<decimal> dealer_income { get; set; }
        public Nullable<decimal> rem_gst { get; set; }
        public Nullable<decimal> whitelabel_gst { get; set; }
        public Nullable<decimal> master_gst { get; set; }
        public Nullable<decimal> dealer_gst { get; set; }
        public Nullable<decimal> admin_gst { get; set; }
        public Nullable<decimal> rem_tds { get; set; }
        public Nullable<decimal> whitelabel_tds { get; set; }
        public Nullable<decimal> master_tds { get; set; }
        public Nullable<decimal> dealer_tds { get; set; }
        public Nullable<decimal> admin_tds { get; set; }
        public string Devicetoken { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
    }
}
