//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remain_superstokist_balance
    {
        public int ID { get; set; }
        public string SuperStokistID { get; set; }
        public Nullable<decimal> Remainamount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
