//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class retailer_operator_code
    {
        public int id { get; set; }
        public string RetailerId { get; set; }
        public string Operator_id { get; set; }
        public string operator_Name { get; set; }
        public bool status { get; set; }
        public Nullable<bool> CreaditStatus { get; set; }
    }
}
