//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerCreationUsedToken
    {
        public int Idno { get; set; }
        public string DealerId { get; set; }
        public string RetaierId { get; set; }
        public string TokenId { get; set; }
        public int RemainTokenPre { get; set; }
        public int RemainTokenPost { get; set; }
    }
}
