//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer_invoice_Numbers
    {
        public int idno { get; set; }
        public string retailerid { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string invoiceno { get; set; }
    }
}
