//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerOutlet
    {
        public int Idno { get; set; }
        public string RetailerId { get; set; }
        public string outlet_id { get; set; }
        public string store_type { get; set; }
        public bool IsKycUploaded { get; set; }
        public bool kyc_status { get; set; }
        public bool outlet_status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<bool> IsPanConfirmed { get; set; }
    
        public virtual Retailer_Details Retailer_Details { get; set; }
    }
}
