//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class retailer_slab
    {
        public int idno { get; set; }
        public string @operator { get; set; }
        public Nullable<decimal> comm { get; set; }
        public string retailer_id { get; set; }
        public string Operator_name { get; set; }
        public Nullable<decimal> commrs { get; set; }
        public Nullable<decimal> maxrs { get; set; }
        public Nullable<decimal> RtlCommPrc { get; set; }
    }
}
