//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roffer_history
    {
        public int idno { get; set; }
        public string retailerid { get; set; }
        public Nullable<decimal> price { get; set; }
        public string number { get; set; }
        public string optcode { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<decimal> sharecomm { get; set; }
        public Nullable<decimal> remainpre { get; set; }
        public Nullable<decimal> remainpost { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public string sts { get; set; }
        public string userPerce { get; set; }
    }
}
