//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schdule_fund
    {
        public int idno { get; set; }
        public string Apiname { get; set; }
        public Nullable<decimal> minfund { get; set; }
        public Nullable<int> maxhours { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> timeset { get; set; }
        public Nullable<int> dailysch { get; set; }
        public Nullable<int> schdulefre { get; set; }
        public string status { get; set; }
        public Nullable<decimal> amount { get; set; }
    }
}
