//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling_Recharge_info
    {
        public int idno { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string optcode { get; set; }
        public string Rstaus { get; set; }
        public Nullable<System.DateTime> Rch_time { get; set; }
        public Nullable<System.DateTime> Resp_time { get; set; }
        public string Rch_from { get; set; }
        public string Dealer_id { get; set; }
        public Nullable<decimal> dealerremain { get; set; }
        public string Recharge_request { get; set; }
        public string Recharge_response { get; set; }
        public string API_Request { get; set; }
        public string API_response { get; set; }
        public Nullable<decimal> income { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string imeino { get; set; }
        public string trans_id { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> tds { get; set; }
        public Nullable<decimal> dlmpre { get; set; }
        public Nullable<decimal> dlmpost { get; set; }
        public string simno { get; set; }
        public Nullable<decimal> purchase { get; set; }
    }
}
