//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sender_aadhar_info
    {
        public int idno { get; set; }
        public string retailerid { get; set; }
        public string sendernumber { get; set; }
        public string aadharno { get; set; }
        public string Name { get; set; }
        public string photo { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> reqtime { get; set; }
        public Nullable<System.DateTime> restime { get; set; }
        public string Statuscode { get; set; }
        public Nullable<decimal> remainpre { get; set; }
        public Nullable<decimal> remainpost { get; set; }
        public Nullable<decimal> charge { get; set; }
        public Nullable<decimal> gst { get; set; }
        public string txnid { get; set; }
    }
}
