//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICES_DATA_INFO
    {
        public int idno { get; set; }
        public string header { get; set; }
        public string INFO { get; set; }
        public string Userid { get; set; }
        public string SERVICESNAME { get; set; }
        public string uniqueid { get; set; }
        public string COUNTCOL { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
