//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slab_name
    {
        public int idno { get; set; }
        public string SlabFor { get; set; }
        public string SlabName { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string createdby { get; set; }
    }
}
