//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slab_Money
    {
        public int idno { get; set; }
        public string type { get; set; }
        public int min { get; set; }
        public int max { get; set; }
        public Nullable<decimal> value { get; set; }
        public string clienttype { get; set; }
        public string Slabname { get; set; }
        public string createdby { get; set; }
        public Nullable<decimal> cashback { get; set; }
    }
}
