//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRS_API
    {
        public int id { get; set; }
        public string apiname { get; set; }
        public string @operator { get; set; }
        public string api { get; set; }
        public string apioptcode { get; set; }
        public string status { get; set; }
        public string api_nm { get; set; }
        public string opt_code { get; set; }
        public Nullable<decimal> Purchase { get; set; }
        public Nullable<decimal> purchase_rs { get; set; }
        public Nullable<decimal> max_rs { get; set; }
        public string purchasetype { get; set; }
    }
}
