//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMaster
    {
        public decimal idno { get; set; }
        public string @operator { get; set; }
        public string Keyword { get; set; }
        public string Mobilepre { get; set; }
        public string Mobilepost { get; set; }
        public string Amountpre { get; set; }
        public string Amountpost { get; set; }
        public string Transpre { get; set; }
        public string Transpost { get; set; }
        public string Statuspre { get; set; }
        public string SMSFrom { get; set; }
        public string Lapubalpre { get; set; }
        public string Lapubalpost { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
    }
}
