//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State_user_Wise_permission
    {
        public int idno { get; set; }
        public string Employeeid { get; set; }
        public string userID { get; set; }
        public Nullable<int> stateid { get; set; }
        public string usertype { get; set; }
        public string permissiontype { get; set; }
        public Nullable<bool> isaccesspermission { get; set; }
    }
}
