//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeDeposit
    {
        public int Idno { get; set; }
        public int InvoiceNo { get; set; }
        public string RollNo { get; set; }
        public string FCID { get; set; }
        public decimal Amount { get; set; }
        public decimal AdminComm { get; set; }
        public decimal MDComm { get; set; }
        public decimal DLMComm { get; set; }
        public decimal REMComm { get; set; }
        public decimal WLComm { get; set; }
        public string Description { get; set; }
        public int InstallmentNo { get; set; }
        public Nullable<System.DateTime> paydate { get; set; }
    }
}
