//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string RollNo { get; set; }
        public string FeeCollectorID { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Board { get; set; }
        public string stdClass { get; set; }
        public string Section { get; set; }
        public string Phone { get; set; }
        public string stdAddress { get; set; }
        public decimal AnnualFee { get; set; }
        public decimal BusFee { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public bool FeeDiscountEnabled { get; set; }
        public bool BusDiscountEnabled { get; set; }
        public string Remark { get; set; }
        public string AcadmicSession { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
