//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Admin_Employee
    {
        public string EmployeeID { get; set; }
        public string Employee_name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string E_mail { get; set; }
        public string AadharCard { get; set; }
        public string PanCard { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> District { get; set; }
        public string city { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
