//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Switch_DealerTOMD
    {
        public int id { get; set; }
        public string DealerID { get; set; }
        public string OLDSuperStockistID { get; set; }
        public string CurrentSuperstockist { get; set; }
        public Nullable<System.DateTime> SwitchDate { get; set; }
    }
}
