//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_permission_Services
    {
        public int ser_id { get; set; }
        public string Servicename { get; set; }
        public string Employee_ID { get; set; }
        public Nullable<bool> isRead { get; set; }
        public Nullable<bool> iswrite { get; set; }
    }
}
