//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAboutUsContent
    {
        public int AboutId { get; set; }
        public string AboutHeading { get; set; }
        public string AboutContent { get; set; }
        public string AboutImage { get; set; }
        public string UserId { get; set; }
        public string Role { get; set; }
    }
}
