//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDTH
    {
        public int Id { get; set; }
        public string lPrice { get; set; }
        public string ActualPrice { get; set; }
        public string HDChannel { get; set; }
        public string GameChannel { get; set; }
        public string Subscription { get; set; }
        public string FreeMonth { get; set; }
        public string Image { get; set; }
        public string UserId { get; set; }
        public string Role { get; set; }
    }
}
