//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDefaultSetTarget
    {
        public int targetID { get; set; }
        public string Categories { get; set; }
        public Nullable<decimal> settarget { get; set; }
        public string OfferType { get; set; }
        public string Achived60 { get; set; }
        public string Achived70 { get; set; }
        public string Achived80 { get; set; }
        public string Achived90 { get; set; }
        public string Achived100 { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
