//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFooterPageContent
    {
        public int Id { get; set; }
        public string FooterPagetype { get; set; }
        public string FooterPageContent { get; set; }
        public string UserId { get; set; }
        public string Role { get; set; }
    }
}
