//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public long Id { get; set; }
        public string MenuName { get; set; }
        public string Status { get; set; }
        public string Users { get; set; }
        public string UserId { get; set; }
        public string Role { get; set; }
    }
}
