//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWhiteLabel_FooterServices
    {
        public int Id { get; set; }
        public string ServiceType { get; set; }
        public string ServiceName1 { get; set; }
        public string ServiceName2 { get; set; }
        public string ServiceName3 { get; set; }
        public string ServiceName4 { get; set; }
        public string ServiceName5 { get; set; }
        public string UserId { get; set; }
    }
}
