//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBO_AirBookingForNonLccDetail
    {
        public int idno { get; set; }
        public decimal FareAmount { get; set; }
        public string PNR { get; set; }
        public string BookingID { get; set; }
        public string ItinerarySource { get; set; }
        public string TraceID { get; set; }
        public decimal AddCharge { get; set; }
        public decimal UpdateFareWithAmt { get; set; }
        public string RetailerId { get; set; }
        public string TicketStatus { get; set; }
        public short TicketStatusCode { get; set; }
        public string RequestJson { get; set; }
        public string ResponseJson { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string LeadPaxFirstName { get; set; }
        public string LeadPaxLastName { get; set; }
        public Nullable<decimal> OfferedFare { get; set; }
        public string PassengerName { get; set; }
        public string AirlineName { get; set; }
        public Nullable<decimal> PublishedFare { get; set; }
    }
}
