//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// TDS (Tax Deducted at Source) ki information store karne wala model — retailer ke liye service-wise TDS data rakhta hai.
    /// </summary>
    public partial class TDSController
    {
        public int idno { get; set; }
        public string Email { get; set; }
        public string DMT { get; set; }
        public string AEPS { get; set; }
        public string MPoss { get; set; }
        public string Flight { get; set; }
        public string Postpaid { get; set; }
        public string Pancard { get; set; }
    }
}
