//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timing_schedule
    {
        public int idno { get; set; }
        public Nullable<int> API_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> s_time { get; set; }
        public string Frequentally { get; set; }
        public string Status { get; set; }
    }
}
