//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update_Aeps_Info
    {
        public int idno { get; set; }
        public string UserId { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<bool> status { get; set; }
        public string RequestFrom { get; set; }
    }
}
