//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upi_info
    {
        public int idno { get; set; }
        public string MID { get; set; }
        public string MerchantVPA { get; set; }
        public string Password { get; set; }
        public string UpiPreFix { get; set; }
    }
}
