//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utility_comm_bytiming
    {
        public int idno { get; set; }
        public Nullable<int> commper { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Typefor { get; set; }
        public Nullable<int> commper1 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
    }
}
