//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utility_extra_comm_Api
    {
        public int idno { get; set; }
        public string optcode { get; set; }
        public Nullable<decimal> move1 { get; set; }
        public Nullable<decimal> move2 { get; set; }
        public Nullable<decimal> move3 { get; set; }
        public Nullable<decimal> move4 { get; set; }
        public Nullable<decimal> move5 { get; set; }
    }
}
