//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VastWeb_upi_txn_deatils
    {
        public int idno { get; set; }
        public string txnid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string status { get; set; }
        public string bankrrn { get; set; }
        public string payeename { get; set; }
        public Nullable<System.DateTime> ndate { get; set; }
    }
}
