//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_details
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public string Name { get; set; }
        public string Firmname { get; set; }
        public int state { get; set; }
        public int district { get; set; }
        public string address { get; set; }
        public string pin { get; set; }
        public string emailid { get; set; }
        public string mobile { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string aadharnumber { get; set; }
        public string pancardnumber { get; set; }
        public string gstnumber { get; set; }
        public string createdby { get; set; }
        public string Photo { get; set; }
        public string Bankaccountno { get; set; }
        public string Ifsccode { get; set; }
        public string city { get; set; }
        public string accountholder { get; set; }
        public string bankname { get; set; }
    }
}
