//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet_imps_master_comm
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> verify_comm { get; set; }
        public Nullable<decimal> comm_1000 { get; set; }
        public Nullable<decimal> comm_2000 { get; set; }
        public Nullable<decimal> comm_3000 { get; set; }
        public Nullable<decimal> comm_4000 { get; set; }
        public Nullable<decimal> comm_5000 { get; set; }
        public Nullable<decimal> comm_6000 { get; set; }
        public Nullable<decimal> comm_7000 { get; set; }
        public Nullable<decimal> comm_8000 { get; set; }
        public Nullable<decimal> comm_9000 { get; set; }
        public Nullable<decimal> comm_10000 { get; set; }
        public Nullable<decimal> comm_11000 { get; set; }
        public Nullable<decimal> comm_12000 { get; set; }
        public Nullable<decimal> comm_13000 { get; set; }
        public Nullable<decimal> comm_14000 { get; set; }
        public Nullable<decimal> comm_15000 { get; set; }
        public Nullable<decimal> comm_16000 { get; set; }
        public Nullable<decimal> comm_17000 { get; set; }
        public Nullable<decimal> comm_18000 { get; set; }
        public Nullable<decimal> comm_19000 { get; set; }
        public Nullable<decimal> comm_20000 { get; set; }
        public Nullable<decimal> comm_21000 { get; set; }
        public Nullable<decimal> comm_22000 { get; set; }
        public Nullable<decimal> comm_23000 { get; set; }
        public Nullable<decimal> comm_24000 { get; set; }
        public Nullable<decimal> comm_25000 { get; set; }
    }
}
