//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletToBankAmountTransferRequest
    {
        public int Idno { get; set; }
        public string RetailerId { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string IfscCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ProcessingCharge { get; set; }
        public string TransferType { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> RemPre { get; set; }
        public Nullable<decimal> RemPost { get; set; }
        public Nullable<decimal> AdminPre { get; set; }
        public Nullable<decimal> AdminPost { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string Email { get; set; }
        public string BankRRN { get; set; }
        public string Remark { get; set; }
        public string type { get; set; }
        public string RequestId { get; set; }
        public Nullable<decimal> Total_Debit { get; set; }
        public string TransectionID { get; set; }
    }
}
