//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whatsapp_user_details
    {
        public int idno { get; set; }
        public string mobile { get; set; }
        public string qrdeatils { get; set; }
        public string userid { get; set; }
        public string loginstatus { get; set; }
        public Nullable<System.DateTime> logintime { get; set; }
        public string servicename { get; set; }
        public Nullable<System.DateTime> purchasedate { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
    }
}
