//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_to_WhitelabelSuper_balance
    {
        public int ID { get; set; }
        public string whitelabelid { get; set; }
        public string SuperStokistID { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> RechargeDate { get; set; }
        public Nullable<decimal> remainsuper { get; set; }
        public Nullable<decimal> commistion { get; set; }
        public Nullable<decimal> remainsuperafter { get; set; }
        public string bal_type { get; set; }
        public Nullable<decimal> oldcrbalance { get; set; }
        public Nullable<decimal> cr { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> fund_transfer { get; set; }
        public string balance_from { get; set; }
        public string CollectionBy { get; set; }
        public string BankName { get; set; }
        public string Admin_AccountNo { get; set; }
        public Nullable<decimal> gst { get; set; }
        public string Head { get; set; }
    }
}
