//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_dlm_opt_code
    {
        public int idno { get; set; }
        public string whitelabel_id { get; set; }
        public string dlmid { get; set; }
        public string optid { get; set; }
        public string opt_name { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
