//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_master_Mpos_comm_details
    {
        public int Idno { get; set; }
        public string Whitelabel { get; set; }
        public string Userid { get; set; }
        public string userRole { get; set; }
        public Nullable<decimal> CashWithdraw { get; set; }
        public Nullable<decimal> salesDebitUpto2000 { get; set; }
        public Nullable<decimal> salesDebitAbove2000 { get; set; }
        public Nullable<decimal> saleCredit { get; set; }
        public Nullable<decimal> saleCreditGrocery { get; set; }
        public Nullable<decimal> saleCreditEduAndIns { get; set; }
        public Nullable<decimal> gst { get; set; }
        public string credit_type { get; set; }
        public Nullable<decimal> prepaidcard { get; set; }
        public Nullable<decimal> maxcashcomm { get; set; }
    }
}
