//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Retailer_Details
    {
        public string DealerId { get; set; }
        public string RetailerId { get; set; }
        public string RetailerName { get; set; }
        public int State { get; set; }
        public int District { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public int Pincode { get; set; }
        public string Email { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string Status { get; set; }
        public string Frm_Name { get; set; }
        public string slab_name { get; set; }
        public string AadharCard { get; set; }
        public string PanCard { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public string gst { get; set; }
        public string moneysts { get; set; }
        public Nullable<decimal> caption { get; set; }
        public string photo { get; set; }
        public string PIN { get; set; }
        public string dateofbirth { get; set; }
        public string PartnerID { get; set; }
        public string AepsMerchandId { get; set; }
        public string AepsMPIN { get; set; }
        public string referralcode { get; set; }
        public string PSAStatus { get; set; }
        public string AepsMposstatus { get; set; }
        public string Position { get; set; }
        public string BusinessType { get; set; }
        public string Bankaccountno { get; set; }
        public string Ifsccode { get; set; }
        public string city { get; set; }
        public string accountholder { get; set; }
        public string bankname { get; set; }
        public string pancardPath { get; set; }
        public string aadharcardPath { get; set; }
        public string frimregistrationPath { get; set; }
        public string Aepskycstatus { get; set; }
        public Nullable<System.DateTime> UpdateprofileDate { get; set; }
        public string AadhaarStatus { get; set; }
        public string AssignByreffercode { get; set; }
        public string Whitelabelid { get; set; }
        public string Agreementpath { get; set; }
        public Nullable<bool> IsAgreement { get; set; }
        public string gststatus { get; set; }
        public string BackSideAadharcardphoto { get; set; }
        public string CretedBy { get; set; }
        public string JoiningTokenId { get; set; }
        public string bankAddress { get; set; }
        public string Registractioncertificatepath { get; set; }
        public string serviceagreementpath { get; set; }
        public string AddressProofpath { get; set; }
        public string Mpossts { get; set; }
        public string Flighsts { get; set; }
        public string Bussts { get; set; }
        public string Hotelsts { get; set; }
        public string pancardsts { get; set; }
        public string Indonepalsts { get; set; }
        public string giftcardsts { get; set; }
        public Nullable<bool> pancardCreaditsts { get; set; }
        public Nullable<bool> AepsMposCreaditstatus { get; set; }
        public Nullable<bool> MposCreaditsts { get; set; }
        public Nullable<bool> FlighCreaditsts { get; set; }
        public Nullable<bool> BusCreaditsts { get; set; }
        public Nullable<bool> HotelCreaditsts { get; set; }
        public Nullable<bool> IndonepalCreaditsts { get; set; }
        public Nullable<bool> giftcardCreaditsts { get; set; }
        public Nullable<bool> moneyCreaditsts { get; set; }
        public string SelfReferalCode { get; set; }
        public string ShopwithSalfie { get; set; }
        public string ShopwithSalfieStatus { get; set; }
        public string microATM_MCC_CODE { get; set; }
    
        public virtual Whitelabel_RetailerOutlets Whitelabel_RetailerOutlets { get; set; }
        public virtual Whitelabel_UserLocation Whitelabel_UserLocation { get; set; }
        public virtual Whitelabel_UserLocation Whitelabel_UserLocation1 { get; set; }
        public virtual Whitelabel_VastBazaarRetailerOutlets Whitelabel_VastBazaarRetailerOutlets { get; set; }
    }
}
