//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_api_name
    {
        public string apiname { get; set; }
        public string api_url { get; set; }
        public string sts { get; set; }
        public string sts_enable { get; set; }
        public string viewbill { get; set; }
        public int idno { get; set; }
        public string whitelabelid { get; set; }
    }
}
