//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_to_Dealer
    {
        public string dealerid { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> admin_prebal { get; set; }
        public Nullable<decimal> admin_postbal { get; set; }
        public Nullable<decimal> dealer_prebal { get; set; }
        public Nullable<decimal> dealer_postbal { get; set; }
        public Nullable<System.DateTime> date_dlm { get; set; }
        public Nullable<decimal> comm { get; set; }
        public string balance_from { get; set; }
        public string bal_type { get; set; }
        public Nullable<decimal> oldcrbalance { get; set; }
        public Nullable<decimal> cr { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> Oldcreditbalance { get; set; }
        public Nullable<decimal> Newbalance { get; set; }
        public string fund_by { get; set; }
        public string CollectionBy { get; set; }
        public string BankName { get; set; }
        public string Admin_AccountNo { get; set; }
        public Nullable<decimal> gst { get; set; }
        public string Head { get; set; }
        public int idno { get; set; }
        public string WhitelabelId { get; set; }
    }
}
