//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_bank_info
    {
        public int idno { get; set; }
        public string banknm { get; set; }
        public string ifsccode { get; set; }
        public string acno { get; set; }
        public string holdername { get; set; }
        public string actype { get; set; }
        public string address { get; set; }
        public string branch_nm { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
