//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_Dealer_Details
    {
        public string Whitelabelid { get; set; }
        public string DealerId { get; set; }
        public string DealerName { get; set; }
        public string FarmName { get; set; }
        public int State { get; set; }
        public int District { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Status { get; set; }
        public string slab_name { get; set; }
        public string pancard { get; set; }
        public string adharcard { get; set; }
        public string gst { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> SignupStatus { get; set; }
        public string FinincialRolesType { get; set; }
        public string masterid { get; set; }
        public string PSAStatus { get; set; }
        public string AadhaarStatus { get; set; }
        public string Agreementpath { get; set; }
        public Nullable<bool> IsAgreement { get; set; }
        public Nullable<System.DateTime> DOF { get; set; }
        public string DefaultStatus { get; set; }
        public string pancardPath { get; set; }
        public string aadharcardPath { get; set; }
        public string frimregistrationPath { get; set; }
        public string gststatus { get; set; }
        public string BackSideAadharcardphoto { get; set; }
        public string createdby { get; set; }
        public Nullable<bool> moneysts { get; set; }
        public string AepsMposstatus { get; set; }
        public string Mpossts { get; set; }
        public string Flighsts { get; set; }
        public string Bussts { get; set; }
        public string Hotelsts { get; set; }
        public string pancardsts { get; set; }
        public string giftcardsts { get; set; }
        public string TransPIN { get; set; }
    }
}
