//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_UserLocation
    {
        public string RetailerId { get; set; }
        public string Lattitude { get; set; }
        public string Longitute { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string country { get; set; }
        public string postal { get; set; }
        public string IP { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Whitelabel_Retailer_Details Whitelabel_Retailer_Details { get; set; }
        public virtual Whitelabel_Retailer_Details Whitelabel_Retailer_Details1 { get; set; }
    }
}
