//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_rem_purchage
    {
        public int idno { get; set; }
        public string frm { get; set; }
        public string remid { get; set; }
        public string paymode { get; set; }
        public string utrno { get; set; }
        public string banknm { get; set; }
        public string branchnm { get; set; }
        public string details { get; set; }
        public decimal amount { get; set; }
        public string sts { get; set; }
        public Nullable<System.DateTime> reqdate { get; set; }
        public Nullable<System.DateTime> responsedate { get; set; }
        public string crests { get; set; }
        public string orderno { get; set; }
        public string type_ { get; set; }
        public Nullable<decimal> comm { get; set; }
        public string Toaccountno { get; set; }
        public string Fromaccountno { get; set; }
        public string Slip { get; set; }
        public string Pancard { get; set; }
        public string Branch { get; set; }
        public string AccountHolderName { get; set; }
        public Nullable<decimal> cashDepositCharge { get; set; }
        public Nullable<decimal> finalAmount { get; set; }
    }
}
