//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Rem_to_rem_fund_transfer
    {
        public string rem_from { get; set; }
        public string rem_to { get; set; }
        public Nullable<decimal> rem_from_old_bal { get; set; }
        public Nullable<decimal> rem_to_old_bal { get; set; }
        public Nullable<decimal> rem_from_new { get; set; }
        public Nullable<decimal> rem_to_new { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string comment { get; set; }
        public int idno { get; set; }
        public string WhitelabelId { get; set; }
    }
}
