//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_to_retailer
    {
        public int idno { get; set; }
        public string retailerid { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> whitelabelpre { get; set; }
        public Nullable<decimal> whitelabelpost { get; set; }
        public Nullable<decimal> retaileridpre { get; set; }
        public Nullable<decimal> retaileridpost { get; set; }
        public System.DateTime transfer_date { get; set; }
        public string baltype { get; set; }
        public Nullable<decimal> oldcrbal { get; set; }
        public string comment { get; set; }
        public string whitelabelid { get; set; }
        public string dealer_id { get; set; }
        public Nullable<decimal> cr { get; set; }
        public Nullable<decimal> Fundvalue { get; set; }
        public string CollectionBy { get; set; }
        public string BankName { get; set; }
        public string Admin_AccountNo { get; set; }
        public string Head { get; set; }
        public Nullable<decimal> Commission { get; set; }
    }
}
