//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Sent_Mail_History
    {
        public int Idno { get; set; }
        public string Mail_Id { get; set; }
        public string SentMsg { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string UserId { get; set; }
    }
}
