//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_DealerSetTarget
    {
        public int dealertargetid { get; set; }
        public string WhitelabelId { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> SetTarget { get; set; }
        public string OfferType { get; set; }
        public string Achive_60 { get; set; }
        public string Achive_70 { get; set; }
        public string Achive_80 { get; set; }
        public string Achive_90 { get; set; }
        public string Achive_100 { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
