//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhiteLabel_userList
    {
        public int Idno { get; set; }
        public string WhiteLabelID { get; set; }
        public string Name { get; set; }
        public string FrmName { get; set; }
        public string Address { get; set; }
        public string aadharnumber { get; set; }
        public string PanCardnumber { get; set; }
        public string GstNumber { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public string SlabName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> moneystatus { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> district { get; set; }
        public string websitename { get; set; }
        public string Photo { get; set; }
        public string localhost { get; set; }
        public string PSAStatus { get; set; }
        public string Position { get; set; }
        public string BusinessType { get; set; }
        public string Bankaccountno { get; set; }
        public string Ifsccode { get; set; }
        public string city { get; set; }
        public string accountholder { get; set; }
        public string bankname { get; set; }
        public string bankAddress { get; set; }
        public string pancardPath { get; set; }
        public string aadharcardPath { get; set; }
        public string frimregistrationPath { get; set; }
        public string AadhaarStatus { get; set; }
        public Nullable<System.DateTime> UpdateprofileDate { get; set; }
        public string Registractioncertificatepath { get; set; }
        public string serviceagreementpath { get; set; }
        public string AddressProofpath { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string AepsMposstatus { get; set; }
        public string Mpossts { get; set; }
        public string Flighsts { get; set; }
        public string Bussts { get; set; }
        public string Hotelsts { get; set; }
        public string pancardsts { get; set; }
        public string Indonepalsts { get; set; }
        public string giftcardsts { get; set; }
        public Nullable<bool> moneysts { get; set; }
        public string gststatus { get; set; }
        public string Agreementpath { get; set; }
        public Nullable<bool> IsAgreement { get; set; }
        public string tannumber { get; set; }
        public string BackSideAadharcardphoto { get; set; }
        public string Support_Email { get; set; }
        public string Support_Mobile { get; set; }
        public string Allow_RoboticsApi { get; set; }
        public string APPLOGIN_STS { get; set; }
    }
}
