//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_dispute_list
    {
        public int idno { get; set; }
        public string rch_from { get; set; }
        public string rch_number { get; set; }
        public string opt { get; set; }
        public string rch_amount { get; set; }
        public Nullable<System.DateTime> rch_time { get; set; }
        public Nullable<System.DateTime> dis_time { get; set; }
        public string rch_id { get; set; }
        public string sts { get; set; }
        public string portno { get; set; }
        public string portnm { get; set; }
        public string dispute_region { get; set; }
        public string comment { get; set; }
        public string Userid { get; set; }
    }
}
