//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhiteLabel_SocialMedia
    {
        public int Id { get; set; }
        public string Userid { get; set; }
        public string UserRole { get; set; }
        public string BadgeType { get; set; }
        public string Url_Link { get; set; }
        public string status { get; set; }
    }
}
