//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class White_label_slab
    {
        public int idno { get; set; }
        public string optid { get; set; }
        public Nullable<decimal> commision_in_rs { get; set; }
        public Nullable<decimal> commision_in_per { get; set; }
    }
}
