//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_retailer_operator_code
    {
        public int idno { get; set; }
        public string whitelabelid { get; set; }
        public string RetailerId { get; set; }
        public Nullable<int> Operator_id { get; set; }
        public string Operator_Name { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> CreaditStatus { get; set; }
    }
}
