//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_retailer_complaint_request
    {
        public int idno { get; set; }
        public string complaintid { get; set; }
        public string subject { get; set; }
        public string complant { get; set; }
        public string response { get; set; }
        public string sts { get; set; }
        public Nullable<System.DateTime> rdate { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> resdate { get; set; }
        public string Emailid { get; set; }
    }
}
