//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Rem_UPI_REQUEST
    {
        public int id { get; set; }
        public string retailerid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string Bankrrn { get; set; }
        public string sender_vpa { get; set; }
        public string UPITXNID { get; set; }
        public Nullable<System.DateTime> transferdate { get; set; }
        public Nullable<System.DateTime> requestdate { get; set; }
        public Nullable<System.DateTime> responsedate { get; set; }
        public string status { get; set; }
        public string whitelabelid { get; set; }
    }
}
