//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_sms_api_entry
    {
        public int idno { get; set; }
        public string apiname { get; set; }
        public string msg { get; set; }
        public string response { get; set; }
        public Nullable<System.DateTime> m_date { get; set; }
        public string messagefor { get; set; }
        public string userid { get; set; }
    }
}
