//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_SentMessage
    {
        public int idno { get; set; }
        public string portno { get; set; }
        public string senderno { get; set; }
        public string msg { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string status { get; set; }
        public string tid { get; set; }
        public string sts { get; set; }
        public string lapuno { get; set; }
        public string webid { get; set; }
    }
}
