//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Upi_txn_details
    {
        public int idno { get; set; }
        public string rolename { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> amt { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> tds { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> txndate { get; set; }
        public Nullable<decimal> remainpre { get; set; }
        public Nullable<decimal> remainpost { get; set; }
        public Nullable<decimal> wlpre { get; set; }
        public Nullable<decimal> wlpost { get; set; }
        public Nullable<decimal> adminpre { get; set; }
        public Nullable<decimal> adminpost { get; set; }
        public Nullable<decimal> charge { get; set; }
        public Nullable<decimal> finalpay { get; set; }
        public string refid { get; set; }
        public string PayerName { get; set; }
        public string PayerVA { get; set; }
        public string BankRRN { get; set; }
        public string whitelabelid { get; set; }
        public string response { get; set; }
        public string Apinm { get; set; }
        public string IPaddress { get; set; }
        public string Devicetoken { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ModelNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string InternetTYPE { get; set; }
        public string Address { get; set; }
    }
}
