//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_RefferalRetailerIncome
    {
        public int RefferalRetailerIncomeID { get; set; }
        public string WhiteLabelId { get; set; }
        public string ParrentRetailerID { get; set; }
        public Nullable<decimal> Benifitrecived { get; set; }
        public string Sharingtype { get; set; }
        public Nullable<decimal> sharingvalue { get; set; }
        public Nullable<decimal> PreParrentRetailerBalance { get; set; }
        public Nullable<decimal> PostParrentRetailerBalance { get; set; }
        public Nullable<System.DateTime> RecivedDate { get; set; }
        public string ChildRetailerID { get; set; }
        public string RefferalType { get; set; }
    }
}
