//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Sending_SMS_Templates
    {
        public int idno { get; set; }
        public string Templateid { get; set; }
        public Nullable<int> SMSAPIID { get; set; }
        public string SMS_TYPE { get; set; }
        public string Templates { get; set; }
        public string whitelabelId { get; set; }
    }
}
