//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Desktop_Popup
    {
        public int idno { get; set; }
        public string whitelabelid { get; set; }
        public string imageurl { get; set; }
        public string sts { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string Heardercontent { get; set; }
    }
}
