//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Change_mobile_email
    {
        public int idno { get; set; }
        public string role { get; set; }
        public string userid { get; set; }
        public string oldemail { get; set; }
        public string newemail { get; set; }
        public string oldmobile { get; set; }
        public string newmobile { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
