//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_Refferalsetting
    {
        public int refferalID { get; set; }
        public string WhitelabelId { get; set; }
        public string ReferalType { get; set; }
        public Nullable<decimal> minimiumimit { get; set; }
        public Nullable<int> expnoofday { get; set; }
        public string SharingType { get; set; }
        public Nullable<decimal> SharingValue { get; set; }
        public string category { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
    }
}
