//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_AEPS_comm_details
    {
        public int Idno { get; set; }
        public string Userid { get; set; }
        public string userRole { get; set; }
        public Nullable<decimal> RS100 { get; set; }
        public Nullable<decimal> RS200 { get; set; }
        public Nullable<decimal> RS500 { get; set; }
        public Nullable<decimal> RS1000 { get; set; }
        public Nullable<decimal> RS2500 { get; set; }
        public Nullable<decimal> RS3000 { get; set; }
        public Nullable<decimal> RS5000 { get; set; }
        public Nullable<decimal> RS10000 { get; set; }
        public bool IsGstApplicable { get; set; }
        public Nullable<decimal> RS3500 { get; set; }
        public string Whitelabelid { get; set; }
        public Nullable<decimal> RS20 { get; set; }
        public Nullable<decimal> RS50 { get; set; }
        public Nullable<decimal> RS2000 { get; set; }
    }
}
