//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_PaymentGatewaycharge
    {
        public int idno { get; set; }
        public Nullable<decimal> Debitupto2000 { get; set; }
        public Nullable<decimal> debitabove2000 { get; set; }
        public Nullable<decimal> rupaydebit { get; set; }
        public Nullable<decimal> creditcard { get; set; }
        public Nullable<decimal> netbanking { get; set; }
        public Nullable<decimal> amex { get; set; }
        public Nullable<decimal> internationalcard { get; set; }
        public Nullable<decimal> wallet { get; set; }
        public Nullable<decimal> UPI { get; set; }
        public Nullable<decimal> prepaidcard { get; set; }
        public string whitelabelid { get; set; }
    }
}
