//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_ekycCheck
    {
        public int idno { get; set; }
        public string userid { get; set; }
        public Nullable<bool> isvalid { get; set; }
        public Nullable<int> primaryKeyId { get; set; }
        public string encodeFPTxnId { get; set; }
        public string mobilenumber { get; set; }
        public string aadharcard { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string devicename { get; set; }
        public string devicesrno { get; set; }
        public string whitelabelid { get; set; }
    }
}
