//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelabel_virtual_remain
    {
        public int idno { get; set; }
        public string whitelabelid { get; set; }
        public Nullable<decimal> remain { get; set; }
        public Nullable<decimal> ParmanentValue { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
