//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelabel_rem_to_whitelabel_rem_fund_transfer
    {
        public int Idno { get; set; }
        public string whitelabel_rem_from { get; set; }
        public string whitelabel_rem_to { get; set; }
        public Nullable<decimal> whitelabel_remfrom_old_bal { get; set; }
        public Nullable<decimal> whitelabel_rem_to_old_bal { get; set; }
        public Nullable<decimal> whitelabel_rem_from_new { get; set; }
        public Nullable<decimal> whitelabel_rem_to_new { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public string comment { get; set; }
        public string whitelabel_ID { get; set; }
    }
}
